-- Many-to-many through table for PromotionalCode.eligible_plans → SubscriptionPlan.
-- If missing (partial DB / faked migrations), deleting a SubscriptionPlan fails with:
--   relation "promotional_codes_eligible_plans" does not exist
--
-- Prefer: python manage.py migrate subscriptions 0007
-- This file mirrors migration 0007_ensure_promotional_codes_eligible_plans_m2m.py

BEGIN;

CREATE TABLE IF NOT EXISTS "promotional_codes_eligible_plans" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "promotionalcode_id" uuid NOT NULL,
    "subscriptionplan_id" uuid NOT NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'promotional_codes_eligib_promotionalcode_id_subsc_fb99437a_uniq'
  ) THEN
    ALTER TABLE "promotional_codes_eligible_plans"
      ADD CONSTRAINT "promotional_codes_eligib_promotionalcode_id_subsc_fb99437a_uniq"
      UNIQUE ("promotionalcode_id", "subscriptionplan_id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'promotional_codes_el_promotionalcode_id_146268cd_fk_promotion'
  ) THEN
    ALTER TABLE "promotional_codes_eligible_plans"
      ADD CONSTRAINT "promotional_codes_el_promotionalcode_id_146268cd_fk_promotion"
      FOREIGN KEY ("promotionalcode_id") REFERENCES "promotional_codes" ("id")
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'promotional_codes_el_subscriptionplan_id_db6425e2_fk_subscript'
  ) THEN
    ALTER TABLE "promotional_codes_eligible_plans"
      ADD CONSTRAINT "promotional_codes_el_subscriptionplan_id_db6425e2_fk_subscript"
      FOREIGN KEY ("subscriptionplan_id") REFERENCES "subscription_plans" ("id")
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "promotional_codes_eligible_plans_promotionalcode_id_146268cd"
  ON "promotional_codes_eligible_plans" ("promotionalcode_id");
CREATE INDEX IF NOT EXISTS "promotional_codes_eligible_plans_subscriptionplan_id_db6425e2"
  ON "promotional_codes_eligible_plans" ("subscriptionplan_id");

COMMIT;
