# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director_dashboard', '0001_initial'),
        ('programs', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorDashboardCache',
            fields=[
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='director_dashboard_app_cache', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active_programs_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('active_cohorts_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_pending', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_readiness', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cohorts_at_risk', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mentors_over_capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mission_bottlenecks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_overdue_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cache_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'director_dashboard_app_cache',
                'ordering': ['-cache_updated_at'],
            },
        ),
        migrations.AddField(
            model_name='directorcohorthealth',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='programs.cohort'),
        ),
        migrations.AddField(
            model_name='directorcohorthealth',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_health_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='directorcohorthealth',
            index=models.Index(fields=['director', 'updated_at'], name='director_co_directo_c520ec_idx'),
        ),
        migrations.AddIndex(
            model_name='directorcohorthealth',
            index=models.Index(fields=['cohort', 'risk_score'], name='director_co_cohort__4d9b3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directorcohorthealth',
            unique_together={('director', 'cohort')},
        ),
    ]
