# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('mpesa', 'M-Pesa'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('visa_mastercard', 'Visa/Mastercard')], db_index=True, max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Enable this payment gateway')),
                ('api_key', models.CharField(blank=True, help_text='Public/API key', max_length=255)),
                ('secret_key', models.CharField(blank=True, help_text='Secret key (encrypted)', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook signing secret', max_length=255)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook endpoint URL')),
                ('test_mode', models.BooleanField(default=True, help_text='Use test/sandbox mode')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional gateway-specific settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'db_table': 'payment_gateways',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('setting_value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
                'db_table': 'payment_settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, help_text='External gateway transaction ID', max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Raw gateway response')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure if status is failed')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='e.g., "free", "starter", "premium"', max_length=50, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free Tier'), ('starter', 'Starter Tier ($3/month)'), ('premium', 'Premium Tier ($7/month)')], db_index=True, help_text='Subscription tier level', max_length=20)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price (NULL for free tier)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('features', models.JSONField(blank=True, default=list, help_text='Feature flags: ["curriculum_read", "profiler_full", "missions", "ai_coach", "portfolio", "talentscope", "mentorship", "marketplace"]')),
                ('ai_coach_daily_limit', models.IntegerField(blank=True, help_text='AI Coach interactions per day (NULL = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('portfolio_item_limit', models.IntegerField(blank=True, help_text='Portfolio items limit (NULL = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('missions_access_type', models.CharField(choices=[('none', 'No Missions'), ('ai_only', 'AI-Only Missions'), ('full', 'Full Missions (including Capstones and Labs)')], default='none', help_text='Type of mission access', max_length=50)),
                ('mentorship_access', models.BooleanField(default=False, help_text='Full mentorship access (group sessions, recordings, reviews)')),
                ('talentscope_access', models.CharField(choices=[('none', 'No Access'), ('basic', 'Basic TalentScope'), ('preview', 'Preview Mode'), ('full', 'Full Analytics (readiness, CV scoring, Mentor Influence Index)')], default='none', help_text='TalentScope access level', max_length=50)),
                ('marketplace_contact', models.BooleanField(default=False, help_text='Enable employer contact via Marketplace')),
                ('enhanced_access_days', models.IntegerField(blank=True, help_text='Enhanced access period in days (e.g., 180 for Starter tier)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(db_index=True, help_text='e.g., "upgrade_instant", "downgrade_end_cycle"', max_length=100, unique=True)),
                ('rule_type', models.CharField(choices=[('upgrade', 'Upgrade Rule'), ('downgrade', 'Downgrade Rule'), ('grace_period', 'Grace Period'), ('enhanced_access', 'Enhanced Access Period')], db_index=True, max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('value', models.JSONField(default=dict, help_text='Rule configuration (e.g., {"days": 7, "action": "downgrade"})')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Rule',
                'verbose_name_plural': 'Subscription Rules',
                'db_table': 'subscription_rules',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trial', 'Trial')], db_index=True, default='trial', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('enhanced_access_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='180 days for starter_enhanced', null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_subscriptions',
            },
        ),
    ]
