# Ensures promotional_codes_eligible_plans exists (M2M for PromotionalCode.eligible_plans).
# Some databases applied 0004 incompletely; deleting SubscriptionPlan then fails on missing through table.

from django.db import migrations


def forwards(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor != 'postgresql':
        return

    with conn.cursor() as cursor:
        cursor.execute(
            """
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_name = 'promotional_codes_eligible_plans'
            );
            """
        )
        if cursor.fetchone()[0]:
            return

    statements = [
        """
        CREATE TABLE "promotional_codes_eligible_plans" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "promotionalcode_id" uuid NOT NULL,
            "subscriptionplan_id" uuid NOT NULL
        );
        """,
        """
        ALTER TABLE "promotional_codes_eligible_plans"
            ADD CONSTRAINT "promotional_codes_eligib_promotionalcode_id_subsc_fb99437a_uniq"
            UNIQUE ("promotionalcode_id", "subscriptionplan_id");
        """,
        """
        ALTER TABLE "promotional_codes_eligible_plans"
            ADD CONSTRAINT "promotional_codes_el_promotionalcode_id_146268cd_fk_promotion"
            FOREIGN KEY ("promotionalcode_id") REFERENCES "promotional_codes" ("id")
            DEFERRABLE INITIALLY DEFERRED;
        """,
        """
        ALTER TABLE "promotional_codes_eligible_plans"
            ADD CONSTRAINT "promotional_codes_el_subscriptionplan_id_db6425e2_fk_subscript"
            FOREIGN KEY ("subscriptionplan_id") REFERENCES "subscription_plans" ("id")
            DEFERRABLE INITIALLY DEFERRED;
        """,
        """
        CREATE INDEX "promotional_codes_eligible_plans_promotionalcode_id_146268cd"
            ON "promotional_codes_eligible_plans" ("promotionalcode_id");
        """,
        """
        CREATE INDEX "promotional_codes_eligible_plans_subscriptionplan_id_db6425e2"
            ON "promotional_codes_eligible_plans" ("subscriptionplan_id");
        """,
    ]

    with conn.cursor() as cursor:
        for sql in statements:
            cursor.execute(sql)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_usersubscription_user_fk_uuid_id'),
    ]

    operations = [
        migrations.RunPython(forwards, noop_reverse),
    ]
