# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0002_initial'),
        ('student_dashboard', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardupdatequeue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentDashboardCache',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dashboard_cache', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('readiness_score', models.DecimalField(decimal_places=2, default=0, help_text='Readiness score 0-100 from TalentScope', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_to_ready_days', models.IntegerField(default=365, help_text='Estimated days to employability', validators=[django.core.validators.MinValueValidator(0)])),
                ('skill_heatmap', models.JSONField(blank=True, default=dict, help_text='Skill scores: {networking: 45, cloud: 22, ...}')),
                ('top_3_gaps', models.JSONField(blank=True, default=list, help_text='Top 3 skill gaps: ["DFIR", "Python", "AWS"]')),
                ('habit_streak_current', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('habit_completion_week', models.DecimalField(decimal_places=2, default=0, help_text='Habit completion percentage for current week', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('goals_active_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goals_completed_week', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('missions_in_progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('missions_in_review', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('missions_completed_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('next_mission_recommended', models.JSONField(blank=True, default=dict, help_text='{id, title, difficulty, est_hours}')),
                ('portfolio_health_score', models.DecimalField(decimal_places=2, default=0, help_text='Portfolio health score 0-100', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('portfolio_items_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('portfolio_items_approved', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('public_profile_enabled', models.BooleanField(default=False)),
                ('public_profile_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('cohort_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('cohort_name', models.CharField(blank=True, max_length=255)),
                ('mentor_name', models.CharField(blank=True, max_length=255)),
                ('next_cohort_event', models.JSONField(blank=True, default=dict, help_text='{title, date, type: "mentorship|submission"}')),
                ('cohort_completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('leaderboard_rank_global', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('leaderboard_rank_cohort', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('notifications_unread', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('notifications_urgent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('curriculum_progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('next_module_title', models.CharField(blank=True, max_length=255)),
                ('ai_coach_nudge', models.TextField(blank=True)),
                ('ai_action_plan', models.JSONField(blank=True, default=list, help_text='Array of prioritized actions')),
                ('days_to_renewal', models.IntegerField(blank=True, null=True)),
                ('can_upgrade_to_premium', models.BooleanField(default=False)),
                ('future_you_persona', models.CharField(blank=True, help_text='e.g., "Cloud Security Architect", "Threat Hunter"', max_length=255)),
                ('recommended_track', models.CharField(blank=True, help_text='Recommended track name from Profiler', max_length=255)),
                ('identity_alignment_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Identity alignment percentage 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_readiness_window', models.CharField(blank=True, help_text='e.g., "Q2 2026"', max_length=50)),
                ('reflections_last_7d', models.IntegerField(default=0, help_text='Number of reflections in last 7 days', validators=[django.core.validators.MinValueValidator(0)])),
                ('goals_completed_pct', models.DecimalField(decimal_places=2, default=0, help_text='Goals completed percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('top_recommendation', models.JSONField(blank=True, default=dict, help_text='{mission_id, priority_reason, title, deadline}')),
                ('urgent_nudges', models.JSONField(blank=True, default=list, help_text='[{type: "habit_broken", action: "..."}]')),
                ('subscription_tier', models.CharField(db_index=True, default='free', help_text='free, starter3, professional7', max_length=50)),
                ('enhanced_access_days_left', models.IntegerField(blank=True, help_text='Days remaining for enhanced access', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('next_billing_date', models.DateField(blank=True, help_text='Next billing date', null=True)),
                ('needs_mentor_feedback', models.BooleanField(default=False)),
                ('payment_overdue', models.BooleanField(default=False)),
                ('profile_incomplete', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_active_at', models.DateTimeField(auto_now_add=True)),
                ('cache_updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When cache was last refreshed')),
            ],
            options={
                'db_table': 'student_dashboard_cache',
                'indexes': [models.Index(fields=['user', 'updated_at'], name='student_das_user_id_107133_idx'), models.Index(fields=['cohort_id'], name='student_das_cohort__1f19d6_idx'), models.Index(fields=['leaderboard_rank_global'], name='student_das_leaderb_40a7b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentMissionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('ai_reviewed', 'AI Reviewed'), ('mentor_review', 'Mentor Review'), ('approved', 'Approved'), ('failed', 'Failed')], db_index=True, default='not_started', max_length=20)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI review score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_score', models.DecimalField(blank=True, decimal_places=2, help_text='Mentor review score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, help_text='submit, revise, complete_next', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_mission_progress',
            },
        ),
        migrations.AddIndex(
            model_name='dashboardupdatequeue',
            index=models.Index(fields=['user', 'priority'], name='dashboard_u_user_id_509c47_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardupdatequeue',
            index=models.Index(fields=['priority', 'queued_at'], name='dashboard_u_priorit_2403cf_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardupdatequeue',
            index=models.Index(fields=['processed_at'], name='dashboard_u_process_376fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmissionprogress',
            index=models.Index(fields=['user', 'status'], name='student_mis_user_id_dc8a79_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmissionprogress',
            index=models.Index(fields=['user', 'updated_at'], name='student_mis_user_id_323b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmissionprogress',
            index=models.Index(fields=['mission', 'status'], name='student_mis_mission_f70600_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmissionprogress',
            unique_together={('user', 'mission')},
        ),
    ]
