# Generated by Django 5.2.9 on 2026-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_email_verification_token_if_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='User metadata and settings'),
        ),
    ]
