# Generated by Django 5.2.10 on 2026-01-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_metadata_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foundations_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='foundations_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
