# Generated by Django 5.2.10 on 2026-01-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_foundations_complete_and_more'),
    ]

    operations = [
    ]
