# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilerResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Overall profiling score 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aptitude_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('behavioral_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aptitude_breakdown', models.JSONField(default=dict, help_text='Category scores: {networking: 85, security: 72, ...}')),
                ('behavioral_traits', models.JSONField(default=dict, help_text='Behavioral analysis: {leadership: 8, teamwork: 9, ...}')),
                ('strengths', models.JSONField(default=list, help_text='Identified strengths')),
                ('areas_for_growth', models.JSONField(default=list, help_text='Areas for improvement')),
                ('recommended_tracks', models.JSONField(default=list, help_text='Recommended tracks: [{track_id: "...", confidence: 0.85, reason: "..."}]')),
                ('learning_path_suggestions', models.JSONField(default=list, help_text='Suggested learning paths')),
                ('och_mapping', models.JSONField(default=dict, help_text='Mapping to OCH system: {tier: 1, foundations: [...], tracks: [...]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profilerresults',
            },
        ),
        migrations.CreateModel(
            name='ProfilerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('aptitude_complete', 'Aptitude Complete'), ('behavioral_complete', 'Behavioral Complete'), ('current_self_complete', 'Current Self Complete'), ('future_you_complete', 'Future You Complete'), ('finished', 'Finished'), ('locked', 'Locked')], db_index=True, default='started', max_length=30)),
                ('session_token', models.CharField(blank=True, db_index=True, help_text='Unique session token for Redis tracking', max_length=64, null=True, unique=True)),
                ('current_section', models.CharField(default='welcome', help_text='Current section: welcome, instructions, aptitude, behavioral, results', max_length=50)),
                ('current_question_index', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('aptitude_responses', models.JSONField(blank=True, default=dict, help_text='Aptitude test responses: {question_id: answer, ...}')),
                ('behavioral_responses', models.JSONField(blank=True, default=dict, help_text='Behavioral test responses: {question_id: answer, ...}')),
                ('current_self_assessment', models.JSONField(blank=True, default=dict, help_text='{skills: {...}, behaviors: {...}, learning_style: {...}}')),
                ('futureyou_persona', models.JSONField(blank=True, default=dict, help_text='{name: "Cyber Sentinel", archetype: "Defender", skills: [...]}')),
                ('aptitude_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall aptitude score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('behavioral_profile', models.JSONField(blank=True, default=dict, help_text='Behavioral analysis: {traits: {...}, strengths: [...], areas_for_growth: [...]}')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='Identified strengths: ["analytical thinking", "problem solving", ...]')),
                ('recommended_track_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('track_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score 0.0-1.0', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Total time spent in seconds')),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profilersessions',
            },
        ),
        migrations.CreateModel(
            name='ProfilerQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('aptitude', 'Aptitude'), ('behavioral', 'Behavioral')], db_index=True, max_length=20)),
                ('answer_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('scale', 'Scale (1-10)'), ('likert', 'Likert Scale'), ('text', 'Text Response'), ('boolean', 'Yes/No')], max_length=20)),
                ('question_text', models.TextField()),
                ('question_order', models.IntegerField(db_index=True, default=0)),
                ('options', models.JSONField(blank=True, default=list, help_text='For multiple choice: ["Option 1", "Option 2", ...]')),
                ('correct_answer', models.JSONField(blank=True, help_text='Correct answer for aptitude questions', null=True)),
                ('points', models.IntegerField(default=1, help_text='Points awarded for correct answer')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags: ["networking", "problem-solving"]')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profilerquestions',
                'ordering': ['question_type', 'question_order'],
                'indexes': [models.Index(fields=['question_type', 'is_active'], name='profilerque_questio_0e4ce6_idx'), models.Index(fields=['category'], name='profilerque_categor_2e0cfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfilerAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_key', models.CharField(db_index=True, help_text='e.g., "skills.networking", "behaviors.discipline"', max_length=255)),
                ('answer', models.JSONField(help_text='Answer data: {value: 7, text: "Experienced with Wireshark"}')),
                ('is_correct', models.BooleanField(blank=True, help_text='For aptitude questions', null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiler.profilerquestion')),
            ],
            options={
                'db_table': 'profileranswers',
            },
        ),
    ]
