# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilerresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiler_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='admin_reset_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reset this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiler_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiler_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilerresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='profiler.profilersession'),
        ),
        migrations.AddField(
            model_name='profileranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiler.profilersession'),
        ),
        migrations.AddIndex(
            model_name='profilersession',
            index=models.Index(fields=['user', 'status'], name='profilerses_user_id_df08ed_idx'),
        ),
        migrations.AddIndex(
            model_name='profilersession',
            index=models.Index(fields=['user', 'is_locked'], name='profilerses_user_id_6da7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='profilersession',
            index=models.Index(fields=['session_token'], name='profilerses_session_c6bc54_idx'),
        ),
        migrations.AddIndex(
            model_name='profilerresult',
            index=models.Index(fields=['user'], name='profilerres_user_id_06d847_idx'),
        ),
        migrations.AddIndex(
            model_name='profilerresult',
            index=models.Index(fields=['session'], name='profilerres_session_e6287c_idx'),
        ),
        migrations.AddIndex(
            model_name='profileranswer',
            index=models.Index(fields=['session', 'question'], name='profilerans_session_9ab3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='profileranswer',
            index=models.Index(fields=['session', 'question_key'], name='profilerans_session_94fc27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profileranswer',
            unique_together={('session', 'question')},
        ),
    ]
