# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('behavior_type', models.CharField(choices=[('study_consistency', 'Study Consistency'), ('mission_completion', 'Mission Completion'), ('reflection_frequency', 'Reflection Frequency'), ('engagement_level', 'Engagement Level'), ('help_seeking', 'Help Seeking'), ('collaboration', 'Collaboration')], db_index=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Behavioral metric value', max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (e.g., time_of_day, duration)')),
                ('source', models.CharField(choices=[('habit_log', 'Habit Log'), ('mission', 'Mission'), ('reflection', 'Reflection'), ('session', 'Mentor Session'), ('system', 'System Event')], default='system', max_length=50)),
                ('source_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ts_behavior_signals',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorInfluence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('submission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Submission rate percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code_quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Code quality score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mission_completion_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Mission completion rate percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall performance score', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('influence_index', models.DecimalField(blank=True, decimal_places=1, help_text='Mentor influence index 0-10', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ts_mentor_influence',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('core_readiness_score', models.DecimalField(decimal_places=2, help_text='Core readiness score 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_readiness_window', models.CharField(blank=True, help_text='e.g., "3-6 months"', max_length=50, null=True)),
                ('learning_velocity', models.DecimalField(blank=True, decimal_places=2, help_text='Learning velocity (points per month)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('career_readiness_stage', models.CharField(choices=[('exploring', 'Exploring'), ('building', 'Building'), ('emerging', 'Emerging'), ('ready', 'Ready')], db_index=True, default='exploring', max_length=20)),
                ('job_fit_score', models.DecimalField(blank=True, decimal_places=2, help_text='Job fit score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hiring_timeline_prediction', models.CharField(blank=True, help_text='e.g., "4-6 months"', max_length=50, null=True)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Breakdown by category (technical, practical, theoretical)')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of identified strengths')),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text='List of identified weaknesses with priorities')),
                ('missing_skills', models.JSONField(blank=True, default=list, help_text='List of missing skills with priorities')),
                ('improvement_plan', models.JSONField(blank=True, default=list, help_text='Improvement plan items')),
                ('track_benchmarks', models.JSONField(blank=True, default=dict, help_text='Track-specific benchmark data')),
                ('snapshot_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ts_readiness_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(db_index=True, max_length=255)),
                ('skill_category', models.CharField(db_index=True, max_length=100)),
                ('mastery_level', models.DecimalField(decimal_places=2, help_text='Mastery level 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hours_practiced', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('mission', 'Mission'), ('course', 'Course'), ('portfolio', 'Portfolio'), ('assessment', 'Assessment'), ('mentor_feedback', 'Mentor Feedback')], default='mission', max_length=50)),
                ('source_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ts_skill_signals',
                'ordering': ['-created_at'],
            },
        ),
    ]
