# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talentscope', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorsignal',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorinfluence',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_influences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorinfluence',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influence_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readinesssnapshot',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillsignal',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='behaviorsignal',
            index=models.Index(fields=['mentee', 'behavior_type'], name='ts_behavior_mentee__a6a256_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorsignal',
            index=models.Index(fields=['mentee', 'recorded_at'], name='ts_behavior_mentee__95b3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorsignal',
            index=models.Index(fields=['behavior_type', 'recorded_at'], name='ts_behavior_behavio_64f87d_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorinfluence',
            index=models.Index(fields=['mentee', 'period_start'], name='ts_mentor_i_mentee__5f6d93_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorinfluence',
            index=models.Index(fields=['mentor', 'period_start'], name='ts_mentor_i_mentor__8b6201_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorinfluence',
            index=models.Index(fields=['mentee', 'mentor'], name='ts_mentor_i_mentee__012070_idx'),
        ),
        migrations.AddIndex(
            model_name='readinesssnapshot',
            index=models.Index(fields=['mentee', 'snapshot_date'], name='ts_readines_mentee__6d1e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='readinesssnapshot',
            index=models.Index(fields=['mentee', 'career_readiness_stage'], name='ts_readines_mentee__199a37_idx'),
        ),
        migrations.AddIndex(
            model_name='readinesssnapshot',
            index=models.Index(fields=['snapshot_date'], name='ts_readines_snapsho_334d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsignal',
            index=models.Index(fields=['mentee', 'skill_category'], name='ts_skill_si_mentee__dc7f74_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsignal',
            index=models.Index(fields=['mentee', 'created_at'], name='ts_skill_si_mentee__8b3934_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsignal',
            index=models.Index(fields=['skill_name', 'skill_category'], name='ts_skill_si_skill_n_11e337_idx'),
        ),
    ]
