# Generated by Django 5.2.8 on 2026-01-27 11:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Full sponsor name', max_length=255)),
                ('sponsor_type', models.CharField(choices=[('university', 'University/Institution'), ('corporate', 'Corporate Partner'), ('scholarship', 'Scholarship Provider')], default='university', help_text='Type of sponsoring organization', max_length=20)),
                ('logo_url', models.URLField(blank=True, help_text='Sponsor logo URL', null=True)),
                ('contact_email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Sponsor website', null=True)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, help_text='State/Province', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sponsors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Cohort display name', max_length=255)),
                ('track_slug', models.CharField(help_text='Primary track (defender, grc, innovation, leadership, offensive)', max_length=50)),
                ('target_size', models.IntegerField(default=100, help_text='Target number of students', validators=[django.core.validators.MinValueValidator(1)])),
                ('students_enrolled', models.IntegerField(default=0, help_text='Current number of enrolled students', validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(blank=True, help_text='Cohort start date', null=True)),
                ('expected_graduation_date', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether cohort is currently active')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Overall cohort completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sponsor_cohorts',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorIntervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intervention_type', models.CharField(choices=[('recipe_nudge', 'Recipe Nudge Deployment'), ('mentor_assignment', 'Mentor Assignment'), ('quiz_unlock', 'Quiz Unlock Assistance'), ('cohort_support', 'Cohort-wide Support')], max_length=20)),
                ('title', models.CharField(help_text='Human-readable intervention description', max_length=255)),
                ('description', models.TextField(help_text='Detailed intervention details')),
                ('ai_trigger_reason', models.TextField(help_text='AI reasoning for this intervention')),
                ('expected_roi', models.DecimalField(decimal_places=2, default=1.0, help_text='Expected ROI multiplier', max_digits=4)),
                ('actual_roi', models.DecimalField(blank=True, decimal_places=2, help_text='Actual ROI achieved', max_digits=4, null=True)),
                ('status', models.CharField(choices=[('deployed', 'Deployed'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='deployed', max_length=20)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sponsor_interventions',
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorStudentCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether student is actively enrolled')),
                ('enrollment_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred')], default='enrolled', max_length=20)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Individual student completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Sponsor notes about this student', null=True)),
            ],
            options={
                'db_table': 'sponsor_student_cohorts',
            },
        ),
        migrations.CreateModel(
            name='SponsorAnalytics',
            fields=[
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='sponsors.sponsor')),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('placement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('roi_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('total_hires', models.IntegerField(default=0)),
                ('hires_last_30d', models.IntegerField(default=0)),
                ('avg_salary_kes', models.IntegerField(default=0, help_text='Average salary in KES')),
                ('avg_readiness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cache_version', models.IntegerField(default=1, help_text='Increment when cache structure changes')),
            ],
            options={
                'db_table': 'sponsor_analytics',
            },
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['slug'], name='sponsors_slug_ad33c3_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['sponsor_type'], name='sponsors_sponsor_4bd83a_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['is_active'], name='sponsors_is_acti_19032e_idx'),
        ),
        migrations.AddField(
            model_name='sponsorcohort',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='sponsors.sponsor'),
        ),
        migrations.AddField(
            model_name='sponsorintervention',
            name='sponsor_cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='sponsors.sponsorcohort'),
        ),
        migrations.AddField(
            model_name='sponsorintervention',
            name='target_students',
            field=models.ManyToManyField(help_text='Students targeted by this intervention', related_name='targeted_interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorstudentcohort',
            name='sponsor_cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='sponsors.sponsorcohort'),
        ),
        migrations.AddField(
            model_name='sponsorstudentcohort',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sponsorcohort',
            index=models.Index(fields=['sponsor', 'is_active'], name='sponsor_coh_sponsor_2a6f83_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcohort',
            index=models.Index(fields=['track_slug'], name='sponsor_coh_track_s_38bd36_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcohort',
            index=models.Index(fields=['start_date'], name='sponsor_coh_start_d_14713f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorcohort',
            unique_together={('sponsor', 'name')},
        ),
        migrations.AddIndex(
            model_name='sponsorintervention',
            index=models.Index(fields=['sponsor_cohort', 'status'], name='sponsor_int_sponsor_61e971_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorintervention',
            index=models.Index(fields=['intervention_type'], name='sponsor_int_interve_18a797_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorintervention',
            index=models.Index(fields=['deployed_at'], name='sponsor_int_deploye_3a6cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorstudentcohort',
            index=models.Index(fields=['sponsor_cohort', 'is_active'], name='sponsor_stu_sponsor_dd3cad_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorstudentcohort',
            index=models.Index(fields=['student', 'enrollment_status'], name='sponsor_stu_student_1aba26_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorstudentcohort',
            index=models.Index(fields=['joined_at'], name='sponsor_stu_joined__6b2bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorstudentcohort',
            index=models.Index(fields=['last_activity_at'], name='sponsor_stu_last_ac_d81961_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorstudentcohort',
            unique_together={('sponsor_cohort', 'student')},
        ),
    ]
