# Generated by Django 5.2.8 on 2026-01-27 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorcohort',
            name='ai_interventions_count',
            field=models.IntegerField(default=0, help_text='Number of AI interventions deployed', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sponsorcohort',
            name='budget_allocated',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Allocated budget in KES', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sponsorcohort',
            name='placement_goal',
            field=models.IntegerField(default=0, help_text='Target number of placements/hires', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sponsorcohort',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('graduated', 'Graduated'), ('archived', 'Archived')], default='active', help_text='Cohort lifecycle status', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsorcohort',
            name='target_completion_date',
            field=models.DateField(blank=True, help_text='Target completion date for the cohort', null=True),
        ),
        migrations.AddIndex(
            model_name='sponsorcohort',
            index=models.Index(fields=['sponsor', 'status'], name='sponsor_coh_sponsor_65e237_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcohort',
            index=models.Index(fields=['status'], name='sponsor_coh_status_236d28_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcohort',
            index=models.Index(fields=['target_completion_date'], name='sponsor_coh_target__921b89_idx'),
        ),
    ]
