# Generated by Django 5.2.8 on 2026-01-27 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_sponsorcohort_ai_interventions_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueShareTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_name', models.CharField(help_text='Company that hired the student', max_length=255)),
                ('role_title', models.CharField(help_text='Job title/role', max_length=255)),
                ('first_year_salary_kes', models.DecimalField(decimal_places=2, help_text='Annual first year salary in KES', max_digits=12)),
                ('revenue_share_3pct', models.DecimalField(decimal_places=2, editable=False, help_text='OCH revenue share (3% of first year salary)', max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Payment status of revenue share', max_length=20)),
                ('paid_date', models.DateTimeField(blank=True, help_text='Date revenue share was paid to sponsor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_shares', to='sponsors.sponsorcohort')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_shares', to='sponsors.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'revenue_share_tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sponsor', 'payment_status'], name='revenue_sha_sponsor_2faefa_idx'), models.Index(fields=['cohort', 'created_at'], name='revenue_sha_cohort__c6f7c4_idx'), models.Index(fields=['employer_name'], name='revenue_sha_employe_df20c5_idx'), models.Index(fields=['payment_status', 'paid_date'], name='revenue_sha_payment_8fa947_idx')],
            },
        ),
        migrations.CreateModel(
            name='SponsorCohortBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_month', models.DateField(help_text='Month being billed (YYYY-MM-01)')),
                ('students_active', models.IntegerField(default=0, help_text='Number of active students this month')),
                ('mentor_sessions', models.IntegerField(default=0, help_text='Number of mentor sessions this month')),
                ('lab_usage_hours', models.IntegerField(default=0, help_text='Lab usage hours this month')),
                ('hires', models.IntegerField(default=0, help_text='Number of hires this month')),
                ('platform_cost', models.DecimalField(decimal_places=2, default=0, help_text='Platform fee (students_active × 20,000 KES)', max_digits=12)),
                ('mentor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Mentor fees (mentor_sessions × 7,000 KES)', max_digits=12)),
                ('lab_cost', models.DecimalField(decimal_places=2, default=0, help_text='Lab costs (lab_usage_hours × 200 KES)', max_digits=12)),
                ('scholarship_cost', models.DecimalField(decimal_places=2, default=0, help_text='Scholarship costs allocated this month', max_digits=12)),
                ('revenue_share_kes', models.DecimalField(decimal_places=2, default=0, help_text='Revenue share from hires (3% of first year salaries)', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total costs (platform + mentor + lab + scholarship)', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, help_text='Net amount due (total_cost - revenue_share)', max_digits=12)),
                ('net_roi', models.DecimalField(blank=True, decimal_places=2, help_text='Return on investment ratio', max_digits=8, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', help_text='Payment status', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date payment was received', null=True)),
                ('invoice_generated', models.BooleanField(default=False, help_text='Whether invoice PDF has been generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor_cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='sponsors.sponsorcohort')),
            ],
            options={
                'db_table': 'sponsor_cohort_billing',
                'ordering': ['-billing_month'],
                'indexes': [models.Index(fields=['sponsor_cohort', 'billing_month'], name='sponsor_coh_sponsor_7b88f4_idx'), models.Index(fields=['billing_month', 'payment_status'], name='sponsor_coh_billing_ef9845_idx'), models.Index(fields=['payment_status'], name='sponsor_coh_payment_4c8113_idx')],
                'unique_together': {('sponsor_cohort', 'billing_month')},
            },
        ),
        migrations.CreateModel(
            name='SponsorFinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('platform_fee', 'Platform Fee'), ('mentor_fee', 'Mentor Fee'), ('lab_cost', 'Lab Cost'), ('scholarship', 'Scholarship'), ('revenue_share', 'Revenue Share'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], help_text='Type of financial transaction', max_length=20)),
                ('description', models.TextField(help_text='Detailed transaction description')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive = income, negative = expense)', max_digits=12)),
                ('currency', models.CharField(default='KES', help_text='Currency code (KES, USD, etc.)', max_length=3)),
                ('period_start', models.DateField(blank=True, help_text='Start date of billing period', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End date of billing period', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', help_text='Transaction status', max_length=20)),
                ('invoice_url', models.URLField(blank=True, help_text='Generated invoice PDF URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='sponsors.sponsorcohort')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='sponsors.sponsor')),
            ],
            options={
                'db_table': 'sponsor_financial_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sponsor', 'status'], name='sponsor_fin_sponsor_d45899_idx'), models.Index(fields=['cohort', 'transaction_type'], name='sponsor_fin_cohort__a89e3f_idx'), models.Index(fields=['period_start', 'period_end'], name='sponsor_fin_period__10697a_idx'), models.Index(fields=['transaction_type', 'status'], name='sponsor_fin_transac_51e56f_idx')],
            },
        ),
    ]
