# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['category', 'is_active'], name='community_b_categor_f11add_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['rarity'], name='community_b_rarity_58e75a_idx'),
        ),
        migrations.AddField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='community.channel'),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.channel'),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collabroom',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collab_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collabroomparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community.collabroom'),
        ),
        migrations.AddField(
            model_name='collabroomparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comment'),
        ),
        migrations.AddField(
            model_name='communitycontribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collabroom',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_rooms', to='community.communityevent'),
        ),
        migrations.AddField(
            model_name='communityreputation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_reputation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community.communityevent'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='followed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='target_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='community.comment'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='community.post'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='target_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='community.post'),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='related_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='community.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post'),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='community.post'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.comment'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.post'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysquad',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='community.channel'),
        ),
        migrations.AddField(
            model_name='studysquad',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_squads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.studysquad'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['slug'], name='community_u_slug_207bab_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['code'], name='community_u_code_73525e_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['is_active', 'is_verified'], name='community_u_is_acti_e7e546_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['engagement_score'], name='community_u_engagem_87d958_idx'),
        ),
        migrations.AddField(
            model_name='studysquad',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='community.university'),
        ),
        migrations.AddField(
            model_name='post',
            name='university',
            field=models.ForeignKey(blank=True, help_text='University this post belongs to (null for global posts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.university'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='community.university'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='community.university'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followed_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='community.university'),
        ),
        migrations.AddField(
            model_name='enterprisecohort',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_cohorts', to='community.university'),
        ),
        migrations.AddField(
            model_name='communityreputation',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_records', to='community.university'),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Host university (null for global events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='community.university'),
        ),
        migrations.AddField(
            model_name='collabroomparticipant',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_participants', to='community.university'),
        ),
        migrations.AddField(
            model_name='collabroom',
            name='universities',
            field=models.ManyToManyField(related_name='collab_rooms', to='community.university'),
        ),
        migrations.AddField(
            model_name='channel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='community.university'),
        ),
        migrations.AddField(
            model_name='universitydomain',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='community.university'),
        ),
        migrations.AddField(
            model_name='universitymembership',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.university'),
        ),
        migrations.AddField(
            model_name='universitymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='community.badge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercommunitystats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['user', 'channel'], name='community_c_user_id_163bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['channel', 'role'], name='community_c_channel_bd8a53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('channel', 'user')},
        ),
        migrations.AddIndex(
            model_name='communitycontribution',
            index=models.Index(fields=['user', 'contribution_type'], name='community_c_user_id_c9f683_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycontribution',
            index=models.Index(fields=['user', '-created_at'], name='community_c_user_id_f80458_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycontribution',
            index=models.Index(fields=['contribution_type', '-created_at'], name='community_c_contrib_0ef5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'status'], name='community_e_event_i_e74dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['user', 'status'], name='community_e_user_id_70fdee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['post', 'option_id'], name='community_p_post_id_7448db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('post', 'user', 'option_id')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='community_c_post_id_2fbac0_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='community_c_author__5294bb_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='community_c_parent__a1f1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='aisummary',
            index=models.Index(fields=['post', '-created_at'], name='community_a_post_id_f15cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='aisummary',
            index=models.Index(fields=['channel', 'summary_type'], name='community_a_channel_72917a_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['post', 'reaction_type'], name='community_r_post_id_ea8323_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['comment', 'reaction_type'], name='community_r_comment_461f79_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user', 'post'], name='community_r_user_id_bd18bc_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user', 'comment'], name='community_r_user_id_f5da0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('user', 'post', 'reaction_type'), name='unique_post_reaction'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment', 'reaction_type'), name='unique_comment_reaction'),
        ),
        migrations.AddIndex(
            model_name='squadmembership',
            index=models.Index(fields=['user', 'squad'], name='community_s_user_id_52b504_idx'),
        ),
        migrations.AddIndex(
            model_name='squadmembership',
            index=models.Index(fields=['squad', 'role'], name='community_s_squad_i_82fe96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='squadmembership',
            unique_together={('squad', 'user')},
        ),
        migrations.AddIndex(
            model_name='studysquad',
            index=models.Index(fields=['university', 'is_active'], name='community_s_univers_0ba5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='studysquad',
            index=models.Index(fields=['circle_level', 'track_key'], name='community_s_circle__5868c5_idx'),
        ),
        migrations.AddIndex(
            model_name='studysquad',
            index=models.Index(fields=['is_open', 'member_count'], name='community_s_is_open_69b434_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['university', 'status', '-created_at'], name='community_p_univers_592dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='community_p_author__439191_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'status'], name='community_p_post_ty_da4788_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility', 'status', '-created_at'], name='community_p_visibil_96e364_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_pinned', '-created_at'], name='community_p_is_pinn_7c7f64_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured', '-created_at'], name='community_p_is_feat_c9e79a_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['moderator', '-created_at'], name='community_m_moderat_2774bf_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['action', '-created_at'], name='community_m_action_fdeca6_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['university', '-created_at'], name='community_m_univers_5ff2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['leaderboard_type', 'scope', 'is_current'], name='community_l_leaderb_6db7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['university', 'leaderboard_type'], name='community_l_univers_6733af_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['period_start', 'period_end'], name='community_l_period__5f0830_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'follow_type'], name='community_f_followe_2b1456_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed_user'], name='community_f_followe_231652_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed_university'], name='community_f_followe_f497c0_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed_tag'], name='community_f_followe_63fd29_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisecohort',
            index=models.Index(fields=['enterprise_id', 'is_active'], name='community_e_enterpr_618bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisecohort',
            index=models.Index(fields=['university', 'is_active'], name='community_e_univers_71f09f_idx'),
        ),
        migrations.AddIndex(
            model_name='communityreputation',
            index=models.Index(fields=['level', '-total_points'], name='community_r_level_83c963_idx'),
        ),
        migrations.AddIndex(
            model_name='communityreputation',
            index=models.Index(fields=['university', '-total_points'], name='community_r_univers_8f4ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='communityreputation',
            index=models.Index(fields=['-weekly_points'], name='community_r_weekly__98d3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['status', 'starts_at'], name='community_e_status_fcee70_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['university', 'status'], name='community_e_univers_00482d_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['event_type', 'status'], name='community_e_event_t_7d36af_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['visibility', 'status'], name='community_e_visibil_8f0af7_idx'),
        ),
        migrations.AddIndex(
            model_name='collabroomparticipant',
            index=models.Index(fields=['room', 'university'], name='community_c_room_id_fc4f75_idx'),
        ),
        migrations.AddIndex(
            model_name='collabroomparticipant',
            index=models.Index(fields=['user', 'room'], name='community_c_user_id_4672d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collabroomparticipant',
            unique_together={('room', 'user')},
        ),
        migrations.AddIndex(
            model_name='collabroom',
            index=models.Index(fields=['status', 'starts_at'], name='community_c_status_c16b44_idx'),
        ),
        migrations.AddIndex(
            model_name='collabroom',
            index=models.Index(fields=['room_type', 'status'], name='community_c_room_ty_4d2029_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['university', 'channel_type'], name='community_c_univers_17229d_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['university', 'is_private', 'is_archived'], name='community_c_univers_f9be29_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['track_key'], name='community_c_track_k_d02f52_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['circle_level'], name='community_c_circle__09c84f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('university', 'slug')},
        ),
        migrations.AddIndex(
            model_name='universitydomain',
            index=models.Index(fields=['domain'], name='community_u_domain_586f37_idx'),
        ),
        migrations.AddIndex(
            model_name='universitydomain',
            index=models.Index(fields=['is_active'], name='community_u_is_acti_6f307e_idx'),
        ),
        migrations.AddIndex(
            model_name='universitymembership',
            index=models.Index(fields=['user', 'is_primary'], name='community_u_user_id_762fed_idx'),
        ),
        migrations.AddIndex(
            model_name='universitymembership',
            index=models.Index(fields=['university', 'status'], name='community_u_univers_cb68c5_idx'),
        ),
        migrations.AddIndex(
            model_name='universitymembership',
            index=models.Index(fields=['role'], name='community_u_role_cb33c3_idx'),
        ),
        migrations.AddIndex(
            model_name='universitymembership',
            index=models.Index(fields=['mapped_method'], name='community_u_mapped__effc62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='universitymembership',
            unique_together={('user', 'university')},
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'is_featured'], name='community_u_user_id_0ba414_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['badge', 'earned_at'], name='community_u_badge_i_27dcb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.AddIndex(
            model_name='usercommunitystats',
            index=models.Index(fields=['total_points'], name='community_u_total_p_00db78_idx'),
        ),
        migrations.AddIndex(
            model_name='usercommunitystats',
            index=models.Index(fields=['global_rank'], name='community_u_global__9e7192_idx'),
        ),
    ]
