import uuid
from datetime import date

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0003_institutional_billing_models'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalPortalAccess',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('role', models.CharField(max_length=20, default='viewer', choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('viewer', 'Viewer')])),
                ('permissions', models.JSONField(default=list, help_text='List of specific permissions: ["seat_management", "reporting", "student_import"]')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to='organizations.institutionalcontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_portal_access', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portal_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institutional_portal_access',
                'unique_together': {('contract', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InstitutionalSeatPool',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('pool_type', models.CharField(max_length=20, default='general', choices=[('general', 'General Pool'), ('department', 'Department Specific'), ('program', 'Program Specific'), ('cohort', 'Cohort Specific')])),
                ('allocated_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], help_text='Total seats purchased/allocated to this pool')),
                ('active_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], help_text='Currently occupied seats')),
                ('reserved_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], help_text='Seats reserved but not yet assigned')),
                ('department', models.CharField(max_length=200, blank=True)),
                ('allowed_tracks', models.JSONField(default=list, help_text='List of track IDs that can use this pool')),
                ('allowed_cohorts', models.JSONField(default=list, help_text='List of cohort IDs that can use this pool')),
                ('auto_recycle', models.BooleanField(default=True, help_text='Automatically recycle seats when students complete/leave')),
                ('recycle_delay_days', models.IntegerField(default=7, help_text='Days to wait before recycling a seat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_pools', to='organizations.institutionalcontract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institutional_seat_pools',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalStudentAllocation',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('status', models.CharField(max_length=20, default='allocated', choices=[('allocated', 'Allocated'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('recycled', 'Recycled')])),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(null=True, blank=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('recycled_at', models.DateTimeField(null=True, blank=True)),
                ('assigned_tracks', models.JSONField(default=list, help_text='List of mandatory track IDs assigned by institution')),
                ('department', models.CharField(max_length=200, blank=True)),
                ('mandatory_tracks_completed', models.JSONField(default=list)),
                ('completion_deadline', models.DateField(null=True, blank=True)),
                ('progress_last_updated', models.DateTimeField(null=True, blank=True)),
                ('notes', models.TextField(blank=True)),
                ('seat_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_allocations', to='organizations.institutionalseatpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_allocations', to=settings.AUTH_USER_MODEL)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_students', to=settings.AUTH_USER_MODEL)),
                ('assigned_cohort', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutional_allocations', to='programs.cohort')),
                ('enrollment', models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocation', to='programs.enrollment')),
            ],
            options={
                'db_table': 'institutional_student_allocations',
                'unique_together': {('seat_pool', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InstitutionalBulkImport',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('successful_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20, default='pending', choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')])),
                ('started_at', models.DateTimeField(null=True, blank=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('import_results', models.JSONField(default=dict, help_text='Detailed results: {created: [], updated: [], failed: [], duplicates: []}')),
                ('error_log', models.JSONField(default=list, help_text='List of errors encountered during processing')),
                ('import_settings', models.JSONField(default=dict, help_text='Import settings: {auto_enroll: bool, send_emails: bool, default_cohort: id}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_imports', to='organizations.institutionalcontract')),
                ('seat_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_imports', to='organizations.institutionalseatpool')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institutional_bulk_imports',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalTrackAssignment',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('assignment_type', models.CharField(max_length=20, default='mandatory', choices=[('mandatory', 'Mandatory'), ('recommended', 'Recommended'), ('optional', 'Optional')])),
                ('status', models.CharField(max_length=20, default='assigned', choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('waived', 'Waived')])),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(null=True, blank=True)),
                ('started_at', models.DateTimeField(null=True, blank=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('progress_percentage', models.DecimalField(max_digits=5, decimal_places=2, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_activity', models.DateTimeField(null=True, blank=True)),
                ('department', models.CharField(max_length=200, blank=True)),
                ('custom_requirements', models.JSONField(default=dict, help_text='Custom completion requirements for this assignment')),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_assignments', to='organizations.institutionalcontract')),
                ('student_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_assignments', to='organizations.institutionalstudentallocation')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_assignments', to='programs.track')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institutional_track_assignments',
                'unique_together': {('student_allocation', 'track')},
            },
        ),
        migrations.CreateModel(
            name='InstitutionalSSO',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('protocol', models.CharField(max_length=20, choices=[('saml2', 'SAML 2.0'), ('oidc', 'OpenID Connect'), ('oauth2', 'OAuth 2.0')])),
                ('provider_name', models.CharField(max_length=200)),
                ('entity_id', models.CharField(max_length=500, blank=True)),
                ('sso_url', models.URLField()),
                ('slo_url', models.URLField(blank=True, help_text='Single Logout URL')),
                ('x509_cert', models.TextField(blank=True, help_text='X.509 Certificate')),
                ('private_key', models.TextField(blank=True, help_text='Private Key (encrypted)')),
                ('auto_enrollment_domains', models.JSONField(default=list, help_text='List of email domains for auto-enrollment: ["university.edu", "school.org"]')),
                ('auto_enrollment_enabled', models.BooleanField(default=False)),
                ('user_provisioning_enabled', models.BooleanField(default=False)),
                ('deprovisioning_enabled', models.BooleanField(default=False)),
                ('attribute_mapping', models.JSONField(default=dict, help_text='SAML/OIDC attribute mapping: {email: "mail", first_name: "givenName"}')),
                ('status', models.CharField(max_length=20, default='draft', choices=[('draft', 'Draft'), ('testing', 'Testing'), ('active', 'Active'), ('disabled', 'Disabled')])),
                ('last_sync', models.DateTimeField(null=True, blank=True)),
                ('sync_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_config', to='organizations.institutionalcontract')),
                ('default_seat_pool', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.institutionalseatpool')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institutional_sso',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalDashboardMetrics',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('total_allocated_seats', models.IntegerField(default=0)),
                ('total_active_seats', models.IntegerField(default=0)),
                ('total_available_seats', models.IntegerField(default=0)),
                ('utilization_rate', models.DecimalField(max_digits=5, decimal_places=2, default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('completed_students', models.IntegerField(default=0)),
                ('withdrawn_students', models.IntegerField(default=0)),
                ('avg_completion_rate', models.DecimalField(max_digits=5, decimal_places=2, default=0)),
                ('avg_progress_percentage', models.DecimalField(max_digits=5, decimal_places=2, default=0)),
                ('students_on_track', models.IntegerField(default=0)),
                ('students_behind', models.IntegerField(default=0)),
                ('mandatory_assignments', models.IntegerField(default=0)),
                ('completed_assignments', models.IntegerField(default=0)),
                ('overdue_assignments', models.IntegerField(default=0)),
                ('cost_per_student', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('avg_completion_time_days', models.IntegerField(default=0)),
                ('certification_rate', models.DecimalField(max_digits=5, decimal_places=2, default=0)),
                ('avg_login_frequency', models.DecimalField(max_digits=5, decimal_places=2, default=0)),
                ('avg_session_duration_minutes', models.IntegerField(default=0)),
                ('last_30_days_activity', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('calculation_duration_seconds', models.IntegerField(default=0)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to='organizations.institutionalcontract')),
            ],
            options={
                'db_table': 'institutional_dashboard_metrics',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalAcademicCalendar',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('calendar_type', models.CharField(max_length=20, choices=[('semester', 'Semester System'), ('quarter', 'Quarter System'), ('trimester', 'Trimester System'), ('fiscal', 'Fiscal Year'), ('custom', 'Custom Calendar')])),
                ('academic_year_start', models.DateField()),
                ('academic_year_end', models.DateField()),
                ('periods', models.JSONField(default=list, help_text='List of academic periods: [{name: "Fall 2024", start: "2024-09-01", end: "2024-12-15"}]')),
                ('break_periods', models.JSONField(default=list, help_text='List of break periods: [{name: "Winter Break", start: "2024-12-16", end: "2025-01-15"}]')),
                ('summer_program_enabled', models.BooleanField(default=False)),
                ('summer_discount_rate', models.DecimalField(max_digits=5, decimal_places=2, default=0, help_text='Percentage discount for summer-only programs')),
                ('billing_aligned_to_calendar', models.BooleanField(default=False)),
                ('billing_period_mapping', models.JSONField(default=dict, help_text='Mapping of billing periods to academic periods')),
                ('timezone', models.CharField(max_length=50, default='UTC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_calendar', to='organizations.institutionalcontract')),
            ],
            options={
                'db_table': 'institutional_academic_calendars',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalInvitation',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('email', models.EmailField(max_length=254, db_index=True)),
                ('first_name', models.CharField(max_length=100, blank=True)),
                ('last_name', models.CharField(max_length=100, blank=True)),
                ('department', models.CharField(max_length=200, blank=True)),
                ('assigned_tracks', models.JSONField(default=list, blank=True)),
                ('status', models.CharField(max_length=20, default='pending', choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')])),
                ('token', models.CharField(max_length=255, unique=True, db_index=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(null=True, blank=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_sent', models.DateTimeField(null=True, blank=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_invitations', to='organizations.institutionalcontract')),
                ('seat_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.institutionalseatpool')),
                ('assigned_cohort', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutional_invitations', to='programs.cohort')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_institutional_invitations', to=settings.AUTH_USER_MODEL)),
                ('accepted_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_institutional_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institutional_invitations',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalSeatForfeiture',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('forfeited_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('forfeited_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255, default='Unused seats forfeited at cohort start')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_forfeitures', to='organizations.institutionalcontract')),
                ('seat_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_forfeitures', to='organizations.institutionalseatpool')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_seat_forfeitures', to='programs.cohort')),
            ],
            options={
                'db_table': 'institutional_seat_forfeitures',
                'unique_together': {('seat_pool', 'cohort')},
            },
        ),
    ]

