# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculumactivity',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='curriculum.curriculummodule'),
        ),
        migrations.AddIndex(
            model_name='curriculumtrack',
            index=models.Index(fields=['code', 'is_active'], name='curriculum__code_4a93ec_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumtrack',
            index=models.Index(fields=['level', 'is_active'], name='curriculum__level_8c6c69_idx'),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='track',
            field=models.ForeignKey(blank=True, help_text='FK to CurriculumTrack', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='curriculumactivity',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='curriculum.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.curriculummodule'),
        ),
        migrations.AddField(
            model_name='curriculumactivity',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='modulemission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_missions', to='curriculum.curriculummodule'),
        ),
        migrations.AddField(
            model_name='reciperecommendation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_recommendations', to='curriculum.curriculummodule'),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermissionprogress',
            name='module_mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.modulemission'),
        ),
        migrations.AddField(
            model_name='usermissionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_mission_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.curriculummodule'),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='current_module',
            field=models.ForeignKey(blank=True, help_text='Current active module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='curriculum.curriculummodule'),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='curriculummodule',
            index=models.Index(fields=['track_key', 'order_index'], name='curriculumm_track_k_f394bd_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculummodule',
            index=models.Index(fields=['track_key', 'is_core'], name='curriculumm_track_k_10406d_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculummodule',
            index=models.Index(fields=['track', 'order_index'], name='curriculumm_track_i_c68cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculummodule',
            index=models.Index(fields=['level', 'entitlement_tier'], name='curriculumm_level_a6d9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order_index'], name='lessons_module__6380c9_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='lessons_lesson__5ca97f_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumactivity',
            index=models.Index(fields=['user', '-created_at'], name='curriculum__user_id_e46302_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='curriculum__activit_4508fa_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumactivity',
            index=models.Index(fields=['track', '-created_at'], name='curriculum__track_i_ef4578_idx'),
        ),
        migrations.AddIndex(
            model_name='modulemission',
            index=models.Index(fields=['module', 'recommended_order'], name='module_miss_module__22c8ce_idx'),
        ),
        migrations.AddIndex(
            model_name='modulemission',
            index=models.Index(fields=['mission_id'], name='module_miss_mission_89472b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modulemission',
            unique_together={('module', 'mission_id')},
        ),
        migrations.AddIndex(
            model_name='reciperecommendation',
            index=models.Index(fields=['module', 'order_index'], name='curriculum__module__28a64d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reciperecommendation',
            unique_together={('module', 'recipe_id')},
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'status'], name='user_lesson_user_id_64b223_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['lesson', 'status'], name='user_lesson_lesson__b56751_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['user', 'status'], name='user_curric_user_id_a6824b_idx'),
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['module_mission', 'status'], name='user_curric_module__5fa6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['mission_submission_id'], name='user_curric_mission_8603a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermissionprogress',
            unique_together={('user', 'module_mission')},
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['user', 'status'], name='user_module_user_id_f0505a_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['module', '-completion_percentage'], name='user_module_module__7b8549_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['user', 'is_blocked'], name='user_module_user_id_55cb70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleprogress',
            unique_together={('user', 'module')},
        ),
        migrations.AddIndex(
            model_name='usertrackprogress',
            index=models.Index(fields=['user', 'track'], name='user_track__user_id_b77a10_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrackprogress',
            index=models.Index(fields=['track', '-completion_percentage'], name='user_track__track_i_ce494f_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrackprogress',
            index=models.Index(fields=['user', '-last_activity_at'], name='user_track__user_id_cedb01_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrackprogress',
            index=models.Index(fields=['circle_level', 'phase'], name='user_track__circle__a0d99c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertrackprogress',
            unique_together={('user', 'track')},
        ),
    ]
