# Generated by Django 5.2.10 on 2026-01-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumtrack',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Tier 0 - Profiler'), (1, 'Tier 1 - Foundations'), (2, 'Tier 2 - Beginner Tracks'), (3, 'Tier 3 - Intermediate Tracks'), (4, 'Tier 4 - Advanced Tracks'), (5, 'Tier 5 - Mastery Tracks'), (6, 'Tier 6 - Cross-Track Programs'), (7, 'Tier 7 - Missions & Recipe Engine'), (8, 'Tier 8 - Platform Ecosystem'), (9, 'Tier 9 - Enterprise & National Intelligence')], db_index=True, default=2, help_text='Academic tier (0-9). Tier 2 = Beginner Tracks'),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='tier2_completion_requirements_met',
            field=models.BooleanField(db_index=True, default=False, help_text='All Tier 2 requirements met'),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='tier2_mentor_approval',
            field=models.BooleanField(default=False, help_text='Mentor approval for Tier 2 completion (optional)'),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='tier2_mini_missions_completed',
            field=models.IntegerField(default=0, help_text='Number of mini-missions completed (Tier 2)'),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='tier2_quizzes_passed',
            field=models.IntegerField(default=0, help_text='Number of quizzes passed (Tier 2)'),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='tier2_reflections_submitted',
            field=models.IntegerField(default=0, help_text='Number of reflections submitted (Tier 2)'),
        ),
    ]
