# Generated by Django 5.2.10 on 2026-01-15 21:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_curriculumtrack_tier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossTrackProgramProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('modules_completed', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('submissions_completed', models.IntegerField(default=0, help_text='Reflections, scenarios, documents submitted')),
                ('all_modules_completed', models.BooleanField(default=False)),
                ('all_reflections_submitted', models.BooleanField(default=False)),
                ('all_quizzes_passed', models.BooleanField(default=False)),
                ('final_summary_submitted', models.BooleanField(default=False, help_text='Final summary activity submitted')),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('total_time_spent_minutes', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(help_text='Cross-track program (tier=6)', on_delete=django.db.models.deletion.CASCADE, related_name='cross_track_progress', to='curriculum.curriculumtrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_track_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cross-Track Program Progress',
                'verbose_name_plural': 'Cross-Track Program Progress',
                'db_table': 'cross_track_program_progress',
                'indexes': [models.Index(fields=['user', 'track'], name='cross_track_user_id_b49a8e_idx'), models.Index(fields=['user', 'is_complete'], name='cross_track_user_id_8b7fa6_idx'), models.Index(fields=['track', '-completion_percentage'], name='cross_track_track_i_e8f0a3_idx')],
                'unique_together': {('user', 'track')},
            },
        ),
        migrations.CreateModel(
            name='CrossTrackSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_type', models.CharField(choices=[('reflection', 'Reflection'), ('scenario', 'Scenario Decision'), ('document', 'Document Upload'), ('portfolio', 'Portfolio Item'), ('quiz', 'Quiz Submission')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], db_index=True, default='draft', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content for reflections, scenario responses')),
                ('document_url', models.URLField(blank=True, help_text='URL to uploaded document (CV, portfolio item, etc.)')),
                ('document_filename', models.CharField(blank=True, max_length=255)),
                ('scenario_choice', models.CharField(blank=True, help_text='Selected choice in scenario', max_length=100)),
                ('scenario_reasoning', models.TextField(blank=True, help_text='Reasoning for scenario choice')),
                ('scenario_metadata', models.JSONField(blank=True, default=dict, help_text='Additional scenario data')),
                ('quiz_answers', models.JSONField(blank=True, default=dict, help_text='Quiz answers')),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_feedback', models.TextField(blank=True)),
                ('mentor_rating', models.IntegerField(blank=True, help_text='Mentor rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mentor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional submission metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_track_submissions', to='curriculum.lesson')),
                ('mentor_reviewed_by', models.ForeignKey(blank=True, help_text='Mentor who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cross_track_submissions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_track_submissions', to='curriculum.curriculummodule')),
                ('track', models.ForeignKey(help_text='Cross-track program (tier=6)', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='curriculum.curriculumtrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_track_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cross-Track Submission',
                'verbose_name_plural': 'Cross-Track Submissions',
                'db_table': 'cross_track_submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'track', '-created_at'], name='cross_track_user_id_ce77d0_idx'), models.Index(fields=['track', 'submission_type', 'status'], name='cross_track_track_i_44de1f_idx'), models.Index(fields=['module', 'submission_type'], name='cross_track_module__fa676d_idx'), models.Index(fields=['status', '-submitted_at'], name='cross_track_status_ba073a_idx')],
            },
        ),
    ]
