# Generated by Django 4.2.26 on 2026-02-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_curriculummodule_supporting_recipes_slug_locked'),
        ('curriculum', '0012_tier5_completion_config'),
    ]

    operations = [
    ]
