# Generated by Django 5.2.9

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_merge_20260211_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='Video URL or placeholder')),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('order_number', models.IntegerField(default=0, help_text='Order within module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='curriculum.curriculummodule')),
            ],
            options={
                'verbose_name': 'Curriculum Video',
                'verbose_name_plural': 'Curriculum Videos',
                'db_table': 'curriculum_videos',
                'ordering': ['module', 'order_number'],
                'unique_together': {('module', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('questions', models.JSONField(help_text='Quiz questions and answers in JSON format')),
                ('pass_threshold', models.IntegerField(default=80, help_text='Passing percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='curriculum.curriculummodule')),
            ],
            options={
                'verbose_name': 'Curriculum Quiz',
                'verbose_name_plural': 'Curriculum Quizzes',
                'db_table': 'curriculum_quizzes',
                'unique_together': {('module', 'slug')},
            },
        ),
    ]
