# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamificationpoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readinessscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cohortprogress',
            index=models.Index(fields=['user', 'cohort_id'], name='cohort_prog_user_id_3ea554_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cohortprogress',
            unique_together={('user', 'cohort_id')},
        ),
        migrations.AddIndex(
            model_name='communityactivity',
            index=models.Index(fields=['-created_at'], name='community_a_created_cb3449_idx'),
        ),
        migrations.AddIndex(
            model_name='communityactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='community_a_activit_e0e8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardevent',
            index=models.Index(fields=['user', 'date', '-created_at'], name='dashboard_e_user_id_32d787_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardevent',
            index=models.Index(fields=['date', 'urgency'], name='dashboard_e_date_c563e1_idx'),
        ),
        migrations.AddIndex(
            model_name='gamificationpoints',
            index=models.Index(fields=['user', '-points'], name='gamificatio_user_id_a378ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamificationpoints',
            unique_together={('user',)},
        ),
        migrations.AddIndex(
            model_name='mentorshipsession',
            index=models.Index(fields=['user', 'next_session_date', '-created_at'], name='mentorship__user_id_7d3b57_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['user', 'status', '-created_at'], name='portfolio_i_user_id_08ed52_idx'),
        ),
        migrations.AddIndex(
            model_name='readinessscore',
            index=models.Index(fields=['user', '-updated_at'], name='readiness_s_user_id_2d7303_idx'),
        ),
    ]
