# Generated by Django 5.2.9 on 2026-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='evidence_files',
            field=models.TextField(blank=True, help_text='JSON array of evidence file objects', null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='item_type',
            field=models.CharField(choices=[('mission', 'Mission'), ('reflection', 'Reflection'), ('certification', 'Certification'), ('github', 'GitHub'), ('thm', 'TryHackMe'), ('external', 'External'), ('other', 'Other')], default='mission', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='skill_tags',
            field=models.TextField(blank=True, help_text='JSON array of skill tags', null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
