# Generated by Django 4.2.28 on 2026-02-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_add_profiler_session_id'),
        ('dashboard', '0003_add_portfolio_fields'),
    ]

    operations = [
    ]
