# Generated by Django 5.2.10 on 2026-01-27 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mentor_slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Mentor biography and experience', null=True)),
                ('expertise_tracks', models.JSONField(blank=True, default=list, help_text='["defender", "grc", "offensive", "innovation", "leadership"]')),
                ('max_students_per_cohort', models.IntegerField(default=25, help_text='Maximum students mentor can handle')),
                ('availability_calendar', models.JSONField(blank=True, default=dict, help_text='Google Calendar integration data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentors',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_slug', models.CharField(help_text='Track being discussed', max_length=50)),
                ('title', models.CharField(help_text='Session title/agenda', max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('meeting_url', models.URLField(blank=True, help_text='Zoom/Google Meet link', null=True)),
                ('notes', models.TextField(blank=True, help_text='Session preparation notes', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student_feedback', models.TextField(blank=True, null=True)),
                ('mentor_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_sessions', to='mentors.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_mentor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_sessions',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorStudentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_slug', models.CharField(help_text='Track: defender, grc, offensive, etc.', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average rating from student (1-5)', max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_assignments', to='mentors.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_mentor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_student_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorStudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_slug', models.CharField(blank=True, max_length=50, null=True)),
                ('note_type', models.CharField(choices=[('strength', 'Strength'), ('improvement', 'Improvement Area'), ('action_item', 'Action Item')], max_length=20)),
                ('content', models.TextField(help_text='Detailed feedback or note content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notes', to='mentors.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_mentor_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_student_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mentor',
            index=models.Index(fields=['mentor_slug'], name='mentors_mentor__adc922_idx'),
        ),
        migrations.AddIndex(
            model_name='mentor',
            index=models.Index(fields=['user'], name='mentors_user_id_f6c127_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['mentor', 'scheduled_at'], name='mentor_sess_mentor__fff555_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['student', 'scheduled_at'], name='mentor_sess_student_277e44_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['status'], name='mentor_sess_status_3841b2_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['scheduled_at'], name='mentor_sess_schedul_4fd2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorstudentassignment',
            index=models.Index(fields=['mentor', 'is_active'], name='mentor_stud_mentor__8b247d_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorstudentassignment',
            index=models.Index(fields=['student', 'is_active'], name='mentor_stud_student_127601_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorstudentassignment',
            index=models.Index(fields=['track_slug'], name='mentor_stud_track_s_b85ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorstudentassignment',
            index=models.Index(fields=['assigned_at'], name='mentor_stud_assigne_af0774_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorstudentassignment',
            unique_together={('mentor', 'student', 'track_slug')},
        ),
        migrations.AddIndex(
            model_name='mentorstudentnote',
            index=models.Index(fields=['mentor'], name='mentor_stud_mentor__a5a3fc_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorstudentnote',
            index=models.Index(fields=['student'], name='mentor_stud_student_212de0_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorstudentnote',
            index=models.Index(fields=['note_type'], name='mentor_stud_note_ty_ef49d1_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorstudentnote',
            index=models.Index(fields=['track_slug'], name='mentor_stud_track_s_04c5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorstudentnote',
            index=models.Index(fields=['created_at'], name='mentor_stud_created_349eaf_idx'),
        ),
    ]
