# Generated by Django 5.2.9 on 2026-01-08 19:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('sector', models.CharField(blank=True, help_text='Industry sector', max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Primary account owner for this employer', on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_employers',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter ($3)'), ('professional', 'Professional ($7)')], default='free', help_text='Current monetization tier used for marketplace visibility', max_length=32)),
                ('readiness_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall career readiness score 0-100', max_digits=5, null=True)),
                ('job_fit_score', models.DecimalField(blank=True, decimal_places=2, help_text='TalentScope job-match score (0-100) for current target role', max_digits=5, null=True)),
                ('hiring_timeline_days', models.IntegerField(blank=True, help_text='Predicted days until hire from TalentScope', null=True)),
                ('profile_status', models.CharField(choices=[('foundation_mode', 'Foundation Mode'), ('emerging_talent', 'Emerging Talent'), ('job_ready', 'Job Ready')], db_index=True, default='foundation_mode', max_length=32)),
                ('primary_role', models.CharField(blank=True, help_text='Target role label (e.g., SOC Analyst)', max_length=255)),
                ('primary_track_key', models.CharField(blank=True, help_text='Curriculum track key associated with this profile', max_length=64)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of key skills/keywords for filtering')),
                ('portfolio_depth', models.CharField(blank=True, help_text='Heuristic label like "basic", "moderate", "deep"', max_length=32)),
                ('is_visible', models.BooleanField(default=False, help_text='If false, profile is never shown in marketplace search')),
                ('employer_share_consent', models.BooleanField(default=False, help_text='Snapshot of employer_share consent scope at last sync')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmployerInterestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('favorite', 'Favorited'), ('shortlist', 'Shortlisted'), ('contact_request', 'Contact Requested')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional structured metadata (e.g., job_id, notes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_logs', to='marketplace.employer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_logs', to='marketplace.marketplaceprofile')),
            ],
            options={
                'db_table': 'marketplace_employer_interest_logs',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=32)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(blank=True, default=list, help_text='List of required skills/keywords')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='marketplace.employer')),
            ],
            options={
                'db_table': 'marketplace_job_postings',
                'indexes': [models.Index(fields=['is_active', 'posted_at'], name='marketplace_is_acti_973ccd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceprofile',
            index=models.Index(fields=['profile_status'], name='marketplace_profile_71b9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceprofile',
            index=models.Index(fields=['tier', 'is_visible'], name='marketplace_tier_6679b3_idx'),
        ),
        migrations.AddIndex(
            model_name='employerinterestlog',
            index=models.Index(fields=['employer', 'action'], name='marketplace_employe_cc9cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='employerinterestlog',
            index=models.Index(fields=['profile', 'action'], name='marketplace_profile_af6c59_idx'),
        ),
    ]
