# Generated by Django 5.2.9 on 2026-01-12 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('accepted', 'Accepted')], db_index=True, default='pending', max_length=32)),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter from applicant')),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated match score based on skills (0-100)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes from employer')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, help_text='When status was last changed', null=True)),
                ('applicant', models.ForeignKey(help_text='Student who applied', on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='marketplace.jobposting')),
            ],
            options={
                'db_table': 'marketplace_job_applications',
                'indexes': [models.Index(fields=['job_posting', 'status'], name='marketplace_job_pos_55db77_idx'), models.Index(fields=['applicant', 'status'], name='marketplace_applica_2289e6_idx'), models.Index(fields=['status', 'applied_at'], name='marketplace_status_a5d27c_idx')],
                'unique_together': {('job_posting', 'applicant')},
            },
        ),
    ]
