# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorDashboardCache',
            fields=[
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sponsor_dashboard_cache', serialize=False, to='organizations.organization')),
                ('seats_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_at_risk', models.IntegerField(default=0, help_text='Seats with <50% completion', validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_used_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_readiness', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('graduates_count', models.IntegerField(default=0, help_text='Completed cohorts', validators=[django.core.validators.MinValueValidator(0)])),
                ('active_cohorts_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('overdue_invoices_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_utilization_cohorts', models.IntegerField(default=0, help_text='Cohorts with <50% utilization', validators=[django.core.validators.MinValueValidator(0)])),
                ('cache_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sponsor_dashboard_cache',
                'ordering': ['-cache_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='SPNSR-ABC123-2026 format', max_length=50, unique=True)),
                ('seats', models.IntegerField(help_text='Number of seats this code provides', validators=[django.core.validators.MinValueValidator(1)])),
                ('value_per_seat', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed value or discount %', max_digits=8, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_usage', models.IntegerField(blank=True, help_text='Maximum number of times this code can be used', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_codes', to='organizations.organization')),
            ],
            options={
                'db_table': 'sponsor_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorCohortDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(max_length=200)),
                ('track_name', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, choices=[('onsite', 'Onsite'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], max_length=20)),
                ('seats_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_sponsored', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_remaining', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_readiness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completion_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('portfolio_health_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('graduates_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('at_risk_count', models.IntegerField(default=0, help_text='Students at risk of dropout', validators=[django.core.validators.MinValueValidator(0)])),
                ('next_milestone', models.JSONField(blank=True, default=dict, help_text='{title, date, type}')),
                ('upcoming_events', models.JSONField(blank=True, default=list)),
                ('flags', models.JSONField(blank=True, default=list, help_text='["low_completion", "budget_alert", etc.]')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_dashboards', to='programs.cohort')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_cohort_dashboards', to='organizations.organization')),
            ],
            options={
                'db_table': 'sponsor_cohort_dashboard',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorStudentAggregates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_anonymized', models.CharField(help_text='"Student #123" unless consent granted', max_length=100)),
                ('readiness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completion_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('portfolio_items', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('consent_employer_share', models.BooleanField(default=False, help_text='Whether student consented to share profile with employer')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_student_aggregates', to='programs.cohort')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_student_aggregates', to='organizations.organization')),
            ],
            options={
                'db_table': 'sponsor_student_aggregates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
