# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsor_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorstudentaggregates',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_aggregates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sponsorcode',
            index=models.Index(fields=['org', 'status'], name='sponsor_cod_org_id_8a84aa_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcode',
            index=models.Index(fields=['code'], name='sponsor_cod_code_bd3b98_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcohortdashboard',
            index=models.Index(fields=['org', 'updated_at'], name='sponsor_coh_org_id_17cd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcohortdashboard',
            index=models.Index(fields=['cohort'], name='sponsor_coh_cohort__18cc6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorcohortdashboard',
            unique_together={('org', 'cohort')},
        ),
        migrations.AddIndex(
            model_name='sponsorstudentaggregates',
            index=models.Index(fields=['org', 'cohort'], name='sponsor_stu_org_id_411bac_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorstudentaggregates',
            index=models.Index(fields=['org', 'consent_employer_share'], name='sponsor_stu_org_id_72a1a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorstudentaggregates',
            unique_together={('org', 'cohort', 'student')},
        ),
    ]
