# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.utils.timezone
import mentorship_coordination.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeMentorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_sessions', models.IntegerField(default=12)),
                ('sessions_used', models.IntegerField(default=0)),
                ('mentor_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menteementorassignments',
            },
        ),
        migrations.CreateModel(
            name='MentorFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('director_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mentorflags',
            },
        ),
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('one_on_one', 'One-on-One'), ('group', 'Group'), ('capstone_review', 'Capstone Review'), ('goal_review', 'Goal Review')], max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('zoom_url', models.URLField(blank=True, help_text='Meeting link (Zoom, Google Meet, etc.)')),
                ('recording_url', models.URLField(blank=True, help_text='Session recording URL')),
                ('transcript_url', models.URLField(blank=True, help_text='Session transcript URL')),
                ('calendar_event_id', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Basic session notes')),
                ('structured_notes', models.JSONField(blank=True, default=dict, help_text='Structured notes with takeaways, action items, etc.')),
                ('outcomes', models.JSONField(blank=True, default=dict)),
                ('attended', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False, help_text='Session was cancelled')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('no_show_reason', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Session closed - notes locked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mentorsessions',
            },
        ),
        migrations.CreateModel(
            name='MentorshipMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, help_text='Unique message identifier', max_length=100, unique=True)),
                ('subject', models.CharField(blank=True, help_text='Message subject (optional)', max_length=200)),
                ('body', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(db_index=True, default=False, help_text='Message archived after mentorship closure')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mentorshipmessages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorWorkQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mission_review', 'Mission Review'), ('goal_feedback', 'Goal Feedback'), ('session_notes', 'Session Notes'), ('risk_flag', 'Risk Flag')], max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('sla_hours', models.IntegerField(default=48)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mentorworkqueue',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Attached file', upload_to=mentorship_coordination.models.upload_message_attachment)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(help_text='MIME type', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messageattachments',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_id', models.CharField(db_index=True, help_text='Unique notification identifier', max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('session_reminder', 'Session Reminder'), ('feedback_reminder', 'Feedback Reminder'), ('milestone_achieved', 'Milestone Achieved'), ('session_cancelled', 'Session Cancelled'), ('session_rescheduled', 'Session Rescheduled'), ('assignment_started', 'Assignment Started'), ('assignment_completed', 'Assignment Completed'), ('custom', 'Custom Notification')], db_index=True, max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('push', 'Push Notification')], db_index=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When notification was delivered', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if notification failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (template_id, provider, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'notificationlogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attended', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, help_text='When mentee joined the session', null=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When mentee left the session', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sessionattendance',
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Overall session rating (1-5)')),
                ('mentor_engagement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Mentor engagement level (1-5)')),
                ('mentor_preparation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Mentor preparation level (1-5)')),
                ('session_value', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Session value/helpfulness (1-5)')),
                ('strengths', models.TextField(blank=True, help_text='What went well')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas for improvement')),
                ('additional_comments', models.TextField(blank=True, help_text='Additional comments')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sessionfeedback',
            },
        ),
        migrations.CreateModel(
            name='SessionNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_takeaways', models.JSONField(blank=True, default=list, help_text='List of key takeaways')),
                ('action_items', models.JSONField(blank=True, default=list, help_text='List of action items with assignees')),
                ('discussion_points', models.TextField(blank=True, help_text='Main discussion points')),
                ('next_steps', models.TextField(blank=True, help_text='Recommended next steps')),
                ('mentor_reflections', models.TextField(blank=True, help_text='Mentor reflections on the session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sessionnotes',
            },
        ),
    ]
