# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorship_coordination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menteementorassignment',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menteementorassignment',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorflag',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorflag',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorship_coordination.menteementorassignment'),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipmessage',
            name='assignment',
            field=models.ForeignKey(help_text='Mentor-mentee assignment this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentorship_coordination.menteementorassignment'),
        ),
        migrations.AddField(
            model_name='mentorshipmessage',
            name='recipient',
            field=models.ForeignKey(help_text='User who receives the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_mentorship_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipmessage',
            name='sender',
            field=models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_mentorship_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorworkqueue',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_work_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorworkqueue',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_queue_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mentorship_coordination.mentorshipmessage'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='assignment',
            field=models.ForeignKey(blank=True, help_text='Mentor-mentee assignment (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mentorship_coordination.menteementorassignment'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient',
            field=models.ForeignKey(help_text='User who receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Related session (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorship_coordination.mentorsession'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='mentorship_coordination.mentorsession'),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_records', to='mentorship_coordination.mentorsession'),
        ),
        migrations.AddField(
            model_name='sessionnotes',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes_detail', to='mentorship_coordination.mentorsession'),
        ),
        migrations.AddIndex(
            model_name='menteementorassignment',
            index=models.Index(fields=['status'], name='menteemento_status_5e3993_idx'),
        ),
        migrations.AddIndex(
            model_name='menteementorassignment',
            index=models.Index(fields=['mentor', 'status'], name='menteemento_mentor__a2fbce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menteementorassignment',
            unique_together={('mentee', 'mentor')},
        ),
        migrations.AddIndex(
            model_name='mentorflag',
            index=models.Index(fields=['mentee'], name='mentorflags_mentee__952626_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorflag',
            index=models.Index(fields=['mentor'], name='mentorflags_mentor__99c111_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorflag',
            index=models.Index(fields=['resolved'], name='mentorflags_resolve_7c6981_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['mentor', 'start_time'], name='mentorsessi_mentor__7ae068_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['mentee', 'start_time'], name='mentorsessi_mentee__303792_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipmessage',
            index=models.Index(fields=['assignment', 'created_at'], name='mentorshipm_assignm_78075e_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipmessage',
            index=models.Index(fields=['sender', 'recipient', 'archived'], name='mentorshipm_sender__07ee15_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipmessage',
            index=models.Index(fields=['is_read', 'created_at'], name='mentorshipm_is_read_ca57c6_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorworkqueue',
            index=models.Index(fields=['mentor', 'status'], name='mentorworkq_mentor__b7ee6a_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorworkqueue',
            index=models.Index(fields=['due_at'], name='mentorworkq_due_at_2823e8_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='messageatta_message_60ade2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_4ec25a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type', 'status'], name='notificatio_notific_c3c0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['assignment', 'created_at'], name='notificatio_assignm_a3ec51_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['session', 'created_at'], name='notificatio_session_7cc27a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['session', 'attended'], name='sessionatte_session_6e7a34_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['mentee', 'session'], name='sessionatte_mentee__495f19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'mentee')},
        ),
        migrations.AddIndex(
            model_name='sessionfeedback',
            index=models.Index(fields=['session', 'mentee'], name='sessionfeed_session_abce82_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionfeedback',
            index=models.Index(fields=['mentor'], name='sessionfeed_mentor__6b6df4_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionfeedback',
            index=models.Index(fields=['submitted_at'], name='sessionfeed_submitt_eed67e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionfeedback',
            unique_together={('session', 'mentee')},
        ),
        migrations.AddIndex(
            model_name='sessionnotes',
            index=models.Index(fields=['session'], name='sessionnote_session_4399de_idx'),
        ),
    ]
