import os
import sys


DDL = [
    """
    CREATE TABLE IF NOT EXISTS "mfa_methods" (
      "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      "method_type" varchar(20) NOT NULL,
      "phone_number" varchar(20) NULL,
      "email" varchar(254) NULL,
      "totp_secret" text NULL,
      "totp_backup_codes" jsonb NOT NULL DEFAULT '[]'::jsonb,
      "enabled" boolean NOT NULL DEFAULT true,
      "is_primary" boolean NOT NULL DEFAULT false,
      "is_verified" boolean NOT NULL DEFAULT false,
      "verified_at" timestamp with time zone NULL,
      "created_at" timestamp with time zone NOT NULL DEFAULT now(),
      "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
      "user_id" bigint NOT NULL
    );
    """,
    "CREATE INDEX IF NOT EXISTS mfa_methods_user_id_idx ON mfa_methods(user_id);",
    """
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'mfa_methods_user_id_fkey'
      ) THEN
        ALTER TABLE mfa_methods
          ADD CONSTRAINT mfa_methods_user_id_fkey
          FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
      END IF;
    END
    $$;
    """,
]


def main() -> int:
    sys.path.insert(0, "/app")
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings.production")
    import django

    django.setup()
    from django.db import connection

    with connection.cursor() as cur:
        for stmt in DDL:
            cur.execute(stmt)
            print("OK", stmt.splitlines()[0].strip()[:80])
        cur.execute("select to_regclass('public.mfa_methods')")
        print("REGCLASS", cur.fetchone()[0])

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

