import argparse
import os
import sys


AUTH_TABLE_DDL = {
    "entitlements": [
        """
        CREATE TABLE IF NOT EXISTS "entitlements" (
          "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          "feature" varchar(100) NOT NULL,
          "granted" boolean NOT NULL,
          "granted_at" timestamp with time zone NOT NULL,
          "expires_at" timestamp with time zone NULL,
          "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
          "user_id" bigint NOT NULL
        );
        """,
        """CREATE INDEX IF NOT EXISTS "entitlement_user_id_cf518c_idx" ON "entitlements" ("user_id", "granted");""",
        """CREATE INDEX IF NOT EXISTS "entitlement_feature_0a7486_idx" ON "entitlements" ("feature");""",
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'entitlements_user_id_feature_5a8d5d8c_uniq'
          ) THEN
            ALTER TABLE "entitlements"
              ADD CONSTRAINT "entitlements_user_id_feature_5a8d5d8c_uniq"
              UNIQUE ("user_id", "feature");
          END IF;
        END
        $$;
        """,
    ],
    "consent_scopes": [
        """
        CREATE TABLE IF NOT EXISTS "consent_scopes" (
          "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          "scope_type" varchar(50) NOT NULL,
          "granted" boolean NOT NULL,
          "granted_at" timestamp with time zone NULL,
          "revoked_at" timestamp with time zone NULL,
          "expires_at" timestamp with time zone NULL,
          "created_at" timestamp with time zone NOT NULL,
          "updated_at" timestamp with time zone NOT NULL,
          "user_id" bigint NOT NULL
        );
        """,
        """CREATE INDEX IF NOT EXISTS "consent_sco_user_id_558b56_idx" ON "consent_scopes" ("user_id", "granted");""",
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'consent_scopes_user_id_scope_type_339686a2_uniq'
          ) THEN
            ALTER TABLE "consent_scopes"
              ADD CONSTRAINT "consent_scopes_user_id_scope_type_339686a2_uniq"
              UNIQUE ("user_id", "scope_type");
          END IF;
        END
        $$;
        """,
    ],
    "audit_logs": [
        """
        CREATE TABLE IF NOT EXISTS "audit_logs" (
          "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          "actor_type" varchar(20) NOT NULL,
          "actor_identifier" varchar(255) NOT NULL,
          "action" varchar(50) NOT NULL,
          "resource_type" varchar(100) NOT NULL,
          "resource_id" varchar(100) NULL,
          "object_id" integer NULL CHECK ("object_id" >= 0),
          "ip_address" inet NULL,
          "user_agent" text NULL,
          "request_id" varchar(100) NULL,
          "changes" jsonb NOT NULL DEFAULT '{}'::jsonb,
          "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
          "result" varchar(20) NOT NULL,
          "error_message" text NULL,
          "timestamp" timestamp with time zone NOT NULL,
          "api_key_id" uuid NULL,
          "content_type_id" integer NULL,
          "user_id" bigint NULL
        );
        """,
        """CREATE INDEX IF NOT EXISTS "audit_logs_user_id_88267f_idx" ON "audit_logs" ("user_id", "timestamp");""",
        """CREATE INDEX IF NOT EXISTS "audit_logs_action_474804_idx" ON "audit_logs" ("action", "timestamp");""",
        """CREATE INDEX IF NOT EXISTS "audit_logs_resourc_bda8a6_idx" ON "audit_logs" ("resource_type", "resource_id");""",
        """CREATE INDEX IF NOT EXISTS "audit_logs_timesta_423be6_idx" ON "audit_logs" ("timestamp");""",
        """CREATE INDEX IF NOT EXISTS "audit_logs_request_298ea7_idx" ON "audit_logs" ("request_id");""",
    ],
    "device_trust": [
        """
        CREATE TABLE IF NOT EXISTS "device_trust" (
          "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          "device_id" uuid NOT NULL UNIQUE,
          "device_name" varchar(255) NOT NULL,
          "device_type" varchar(50) NOT NULL,
          "device_fingerprint" varchar(255) NOT NULL,
          "ip_address" inet NULL,
          "user_agent" text NULL,
          "trusted_at" timestamp with time zone NOT NULL,
          "last_used_at" timestamp with time zone NOT NULL,
          "expires_at" timestamp with time zone NULL,
          "revoked_at" timestamp with time zone NULL,
          "user_id" bigint NOT NULL
        );
        """,
        """CREATE INDEX IF NOT EXISTS "device_trus_user_id_a69c8a_idx" ON "device_trust" ("user_id", "trusted_at");""",
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'device_trust_user_id_device_fingerprint_7069f977_uniq'
          ) THEN
            ALTER TABLE "device_trust"
              ADD CONSTRAINT "device_trust_user_id_device_fingerprint_7069f977_uniq"
              UNIQUE ("user_id", "device_fingerprint");
          END IF;
        END
        $$;
        """,
    ],
    "mfa_codes": [
        """
        CREATE TABLE IF NOT EXISTS "mfa_codes" (
          "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          "code" varchar(10) NOT NULL,
          "method" varchar(20) NOT NULL,
          "expires_at" timestamp with time zone NOT NULL,
          "used" boolean NOT NULL,
          "used_at" timestamp with time zone NULL,
          "created_at" timestamp with time zone NOT NULL,
          "ip_address" inet NULL,
          "user_id" bigint NOT NULL
        );
        """,
        """CREATE INDEX IF NOT EXISTS "mfa_codes_user_id_02928a_idx" ON "mfa_codes" ("user_id", "code", "used");""",
        """CREATE INDEX IF NOT EXISTS "mfa_codes_expires_2a908b_idx" ON "mfa_codes" ("expires_at");""",
    ],
    "user_sessions": [
        """
        CREATE TABLE IF NOT EXISTS "user_sessions" (
          "id" uuid NOT NULL PRIMARY KEY,
          "device_fingerprint" varchar(255) NOT NULL,
          "device_name" varchar(255) NULL,
          "device_type" varchar(50) NULL,
          "ip_address" inet NULL,
          "ua" text NULL,
          "refresh_token_hash" varchar(64) NOT NULL UNIQUE,
          "is_trusted" boolean NOT NULL,
          "trusted_at" timestamp with time zone NULL,
          "mfa_verified" boolean NOT NULL,
          "risk_score" double precision NOT NULL,
          "created_at" timestamp with time zone NOT NULL,
          "last_activity" timestamp with time zone NOT NULL,
          "expires_at" timestamp with time zone NOT NULL,
          "revoked_at" timestamp with time zone NULL,
          "user_id" bigint NOT NULL
        );
        """,
        """CREATE INDEX IF NOT EXISTS "user_sessio_user_id_e66ad8_idx" ON "user_sessions" ("user_id", "is_trusted");""",
        """CREATE INDEX IF NOT EXISTS "user_sessio_expires_66ae96_idx" ON "user_sessions" ("expires_at");""",
        """CREATE INDEX IF NOT EXISTS "user_sessio_device__4dc2be_idx" ON "user_sessions" ("device_fingerprint");""",
    ],
}


def main() -> int:
    ap = argparse.ArgumentParser(description="Ensure core auth tables exist in Postgres.")
    ap.add_argument("--tables", default="audit_logs,consent_scopes,device_trust,entitlements,mfa_codes,user_sessions")
    args = ap.parse_args()

    tables = [t.strip() for t in args.tables.split(",") if t.strip()]

    # When executed as `/app/scripts/foo.py`, Python may not include `/app` on sys.path.
    # Ensure the Django project root is importable.
    sys.path.insert(0, "/app")

    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings.production")
    import django

    django.setup()
    from django.db import connection

    with connection.cursor() as cur:
        for t in tables:
            cur.execute("select to_regclass(%s)", [f"public.{t}"])
            exists = cur.fetchone()[0]
            if exists:
                print(f"OK:exists:{t}")
                continue
            for stmt in AUTH_TABLE_DDL.get(t, []):
                cur.execute(stmt)
            print(f"OK:created:{t}")

    with connection.cursor() as cur:
        for t in tables:
            cur.execute("select to_regclass(%s)", [f"public.{t}"])
            print(f"CHECK:{t}={cur.fetchone()[0]}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

