import os
import sys


DDL = [
    # Base table created in organizations.0001_initial
    """
    CREATE TABLE IF NOT EXISTS "organization_members" (
      "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      "role" varchar(20) NOT NULL DEFAULT 'member',
      "joined_at" timestamp with time zone NOT NULL DEFAULT now()
    );
    """,
    # Fields/constraints added by organizations.0002_initial
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS organization_id bigint NULL;",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS user_id bigint NULL;",
    """
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'organization_members_organization_id_fkey'
      ) THEN
        ALTER TABLE organization_members
          ADD CONSTRAINT organization_members_organization_id_fkey
          FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
      END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'organization_members_user_id_fkey'
      ) THEN
        ALTER TABLE organization_members
          ADD CONSTRAINT organization_members_user_id_fkey
          FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
      END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'organization_members_organization_id_user_id_uniq'
      ) THEN
        ALTER TABLE organization_members
          ADD CONSTRAINT organization_members_organization_id_user_id_uniq
          UNIQUE (organization_id, user_id);
      END IF;
    END
    $$;
    """,
    "CREATE INDEX IF NOT EXISTS organization_members_organization_id_idx ON organization_members(organization_id);",
    "CREATE INDEX IF NOT EXISTS organization_members_user_id_idx ON organization_members(user_id);",
]


def main() -> int:
    sys.path.insert(0, "/app")
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings.production")
    import django

    django.setup()
    from django.db import connection

    with connection.cursor() as cur:
        for stmt in DDL:
            cur.execute(stmt)
            print("OK", stmt.splitlines()[0].strip()[:80])

        cur.execute("select to_regclass('public.organization_members')")
        print("REGCLASS", cur.fetchone()[0])

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

