# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, help_text='e.g., "Write Basic Sigma Rule"', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('summary', models.TextField(help_text='1-2 sentence overview', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed "what this solves"')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20)),
                ('estimated_minutes', models.IntegerField(help_text='Estimated completion time (5-60 minutes)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('track_codes', models.JSONField(blank=True, default=list, help_text='Array of track codes like ["SOCDEFENSE", "DFIR"]')),
                ('skill_codes', models.JSONField(default=list, help_text='Array of skill codes like ["SIEM_RULE_WRITING", "LOG_ANALYSIS"]')),
                ('tools_used', models.JSONField(blank=True, default=list, help_text='Array of tools like ["sigma", "jq", "awk"]')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='Other recipes or knowledge prerequisites')),
                ('content', models.JSONField(help_text='Structured steps with sections: intro, prerequisites, steps, validation')),
                ('validation_steps', models.JSONField(blank=True, default=dict, help_text="How to know you're done - validation criteria")),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('mentor_curated', models.BooleanField(db_index=True, default=False)),
                ('usage_count', models.IntegerField(db_index=True, default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'db_table': 'recipes',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeContextLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('mission', 'Mission'), ('module', 'Module'), ('project', 'Project'), ('mentor_session', 'Mentor Session')], db_index=True, max_length=20)),
                ('context_id', models.UUIDField(db_index=True, help_text='mission_id, module_id, etc')),
                ('is_required', models.BooleanField(default=False, help_text='Required vs recommended')),
                ('position_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe Context Link',
                'verbose_name_plural': 'Recipe Context Links',
                'db_table': 'recipe_context_links',
            },
        ),
        migrations.CreateModel(
            name='UserRecipeBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Recipe Bookmark',
                'verbose_name_plural': 'User Recipe Bookmarks',
                'db_table': 'user_recipe_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='UserRecipeProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('bookmarked', 'Bookmarked')], db_index=True, default='started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, help_text='User rating 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, help_text='Student feedback')),
                ('time_spent_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Recipe Progress',
                'verbose_name_plural': 'User Recipe Progress',
                'db_table': 'user_recipe_progress',
            },
        ),
    ]
