# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipecontextlink',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_links', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='userrecipebookmark',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='userrecipebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrecipeprogress',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='userrecipeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='recipes_slug_eff228_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_active', 'usage_count'], name='recipes_is_acti_942594_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty', 'is_active'], name='recipes_difficu_9b5626_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['track_codes'], name='recipes_track_c_467f11_gin'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['skill_codes'], name='recipes_skill_c_ab6b79_gin'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tools_used'], name='recipes_tools_u_738189_gin'),
        ),
        migrations.AddIndex(
            model_name='recipecontextlink',
            index=models.Index(fields=['context_type', 'context_id', 'position_order'], name='recipe_cont_context_a14c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='recipecontextlink',
            index=models.Index(fields=['recipe', 'context_type'], name='recipe_cont_recipe__d43c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecipebookmark',
            index=models.Index(fields=['user', '-bookmarked_at'], name='user_recipe_user_id_0ee536_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrecipebookmark',
            unique_together={('user', 'recipe')},
        ),
        migrations.AddIndex(
            model_name='userrecipeprogress',
            index=models.Index(fields=['user', 'status'], name='user_recipe_user_id_e75ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecipeprogress',
            index=models.Index(fields=['recipe', 'status'], name='user_recipe_recipe__6f1dd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrecipeprogress',
            unique_together={('user', 'recipe')},
        ),
    ]
