# Generated by Django 5.2.8 on 2026-01-18 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('type', models.CharField(choices=[('markdown_repo', 'Markdown Repository'), ('notion', 'Notion'), ('lab_api', 'Lab API'), ('doc_url', 'Document URL'), ('internal_docs', 'Internal Docs')], db_index=True, max_length=20)),
                ('config', models.JSONField(help_text='API keys, paths, selectors, credentials')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe Source',
                'verbose_name_plural': 'Recipe Sources',
                'db_table': 'recipe_sources',
                'indexes': [models.Index(fields=['type', 'active'], name='recipe_sour_type_7199c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecipeNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('reminder', 'Progress Reminder'), ('recommendation', 'Recipe Recommendation'), ('follow_up', 'Follow-up'), ('completion', 'Completion Congrats')], db_index=True, max_length=20)),
                ('payload', models.JSONField(help_text='Notification content and metadata')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe Notification',
                'verbose_name_plural': 'Recipe Notifications',
                'db_table': 'recipe_notifications',
                'indexes': [models.Index(fields=['user', 'sent_at'], name='recipe_noti_user_id_b3abb5_idx'), models.Index(fields=['type', 'created_at'], name='recipe_noti_type_794757_idx'), models.Index(fields=['recipe', 'type'], name='recipe_noti_recipe__c26da1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecipeLLMJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_code', models.CharField(db_index=True, max_length=50)),
                ('level', models.CharField(db_index=True, max_length=20)),
                ('skill_code', models.CharField(db_index=True, max_length=100)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('llm_generated', 'LLM Generated'), ('external_doc', 'External Doc'), ('lab_platform', 'Lab Platform'), ('community', 'Community')], max_length=20)),
                ('input_text', models.TextField(help_text='Raw content to process')),
                ('llm_model', models.CharField(default='gpt-4', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_jobs', to='recipes.recipe')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_jobs', to='recipes.recipesource')),
            ],
            options={
                'verbose_name': 'Recipe LLM Job',
                'verbose_name_plural': 'Recipe LLM Jobs',
                'db_table': 'recipe_llm_jobs',
                'indexes': [models.Index(fields=['status', 'created_at'], name='recipe_llm__status_b51f8b_idx'), models.Index(fields=['track_code', 'skill_code', 'level'], name='recipe_llm__track_c_09fe02_idx'), models.Index(fields=['source', 'status'], name='recipe_llm__source__d1207b_idx')],
            },
        ),
    ]
