# Generated by Django 5.2.8 on 2026-01-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipesource_recipenotification_recipellmjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='inputs',
            field=models.JSONField(default=list, help_text='What the learner needs (log locations, alert IDs, dataset paths)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(default=list, help_text='Array of step objects with step_number, instruction, expected_outcome, evidence_hint'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tools_and_environment',
            field=models.JSONField(default=list, help_text='Array of named tools, SIEMs, OS, labs, log types, etc.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='validation_checks',
            field=models.JSONField(default=list, help_text='Simple questions or checks to confirm skill execution'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy structured content - deprecated'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='2-3 sentence summary of what this recipe teaches'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prerequisites',
            field=models.JSONField(default=list, help_text='Array of prerequisite knowledge or tools'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='validation_steps',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy validation steps - deprecated'),
        ),
    ]
