# Generated by Django 5.2.8 on 2026-01-18 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_inputs_recipe_steps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_free_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='Free tier access'),
        ),
        migrations.AlterField(
            model_name='userrecipeprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_free_sample'], name='idx_recipes_free'),
        ),
    ]
