# Generated by Django 5.2.8 on 2026-01-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_add_free_sample_and_update_status'),
    ]

    operations = [
    ]
