# Generated by Django 4.2.28 on 2026-02-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_add_recipe_type'),
        ('recipes', '0006_create_tables'),
    ]

    operations = [
    ]
