# Generated by Django 5.2.10 on 2026-01-15 09:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationsModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('video', 'Video'), ('interactive', 'Interactive'), ('assessment', 'Assessment'), ('reflection', 'Reflection')], default='video', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='Video URL for video modules', null=True)),
                ('diagram_url', models.URLField(blank=True, help_text='Diagram/image URL', null=True)),
                ('content', models.TextField(blank=True, help_text='Markdown or HTML content')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Must be completed to finish Foundations')),
                ('estimated_minutes', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foundations Module',
                'verbose_name_plural': 'Foundations Modules',
                'db_table': 'foundations_modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FoundationsProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('modules_completed', models.JSONField(blank=True, default=dict, help_text='Module completion data: {module_id: {completed: bool, watch_percentage: float, completed_at: iso}}')),
                ('assessment_score', models.DecimalField(blank=True, decimal_places=2, help_text='Orientation assessment score', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assessment_attempts', models.IntegerField(default=0)),
                ('goals_reflection', models.TextField(blank=True, help_text='User-submitted goals and reflection text')),
                ('value_statement', models.TextField(blank=True, help_text='Value statement from profiler (synced)')),
                ('confirmed_track_key', models.CharField(blank=True, help_text='User-confirmed track (from profiler recommendation or override)', max_length=50)),
                ('track_override', models.BooleanField(default=False, help_text='User overrode profiler recommendation')),
                ('total_time_spent_minutes', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transitioned_to_tier2_at', models.DateTimeField(blank=True, null=True)),
                ('drop_off_module_id', models.UUIDField(blank=True, help_text='Module where user dropped off', null=True)),
                ('last_accessed_module_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foundations_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foundations Progress',
                'verbose_name_plural': 'Foundations Progress',
                'db_table': 'foundations_progress',
            },
        ),
    ]
