# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        # Tables already created via SQL script
        migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
    ]