# Generated by Django 4.2.29 on 2026-03-30 05:23
# Adds certificate renewal fields to existing Certificate table

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_cohort_public_registration'),
    ]

    operations = [
        # Add status field with renewal lifecycle states
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'ACTIVE'),
                    ('renewal_pending', 'RENEWAL_PENDING'),
                    ('grace_period', 'GRACE_PERIOD'),
                    ('expired', 'EXPIRED'),
                    ('renewed', 'RENEWED'),
                    ('suspended', 'SUSPENDED'),
                ],
                default='active',
                help_text='Certificate lifecycle status',
                max_length=20
            ),
        ),
        
        # Add issue_date field
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(
                help_text='Original date of certificate issuance',
                null=True,
                blank=True
            ),
        ),
        
        # Add expiry_date field
        migrations.AddField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateField(
                help_text='Current expiry date (recalculated on renewal)',
                null=True,
                blank=True
            ),
        ),
        
        # Add renewal_count field
        migrations.AddField(
            model_name='certificate',
            name='renewal_count',
            field=models.IntegerField(
                default=0,
                help_text='Number of times this certificate has been renewed'
            ),
        ),
        
        # Add last_renewal_date field
        migrations.AddField(
            model_name='certificate',
            name='last_renewal_date',
            field=models.DateField(
                blank=True,
                help_text='Date of most recent renewal',
                null=True
            ),
        ),
        
        # Add last_renewal_method field
        migrations.AddField(
            model_name='certificate',
            name='last_renewal_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('activity', 'ACTIVITY'),
                    ('mission', 'MISSION'),
                    ('contribution_and_mission', 'CONTRIBUTION_AND_MISSION'),
                ],
                help_text='Method used for last renewal',
                max_length=30,
                null=True
            ),
        ),
        
        # Add renewal_mission foreign key
        migrations.AddField(
            model_name='certificate',
            name='renewal_mission',
            field=models.ForeignKey(
                blank=True,
                help_text='Reference to renewal mission record',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='renewal_certificates',
                to='missions.mission'
            ),
        ),
        
        # Add next_notification_date field
        migrations.AddField(
            model_name='certificate',
            name='next_notification_date',
            field=models.DateField(
                blank=True,
                help_text='Date of next scheduled renewal reminder email',
                null=True
            ),
        ),
        
        # Add grace_period_end field
        migrations.AddField(
            model_name='certificate',
            name='grace_period_end',
            field=models.DateField(
                blank=True,
                help_text='End date of grace period (expiry_date + 30 days)',
                null=True
            ),
        ),
        
        # Add total_hours field
        migrations.AddField(
            model_name='certificate',
            name='total_hours',
            field=models.IntegerField(
                default=0,
                help_text='Total learning hours logged'
            ),
        ),
        
        # Add missions_completed field
        migrations.AddField(
            model_name='certificate',
            name='missions_completed',
            field=models.IntegerField(
                default=0,
                help_text='Total missions completed in track'
            ),
        ),
        
        # Add grade field
        migrations.AddField(
            model_name='certificate',
            name='grade',
            field=models.CharField(
                blank=True,
                help_text='Grade achieved',
                max_length=10
            ),
        ),
        
        # Add template_used field
        migrations.AddField(
            model_name='certificate',
            name='template_used',
            field=models.CharField(
                default='default',
                help_text='Certificate template used',
                max_length=100
            ),
        ),
        
        # Add updated_at field
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True
            ),
        ),
        
        # Add indexes for efficient queries
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status', 'expiry_date'], name='cert_status_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['next_notification_date'], name='cert_notify_date_idx'),
        ),
    ]
