# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, help_text='AI score 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of strengths')),
                ('gaps', models.JSONField(blank=True, default=list, help_text='List of gaps')),
                ('suggestions', models.JSONField(blank=True, default=list, help_text='List of suggestions')),
                ('competencies_detected', models.JSONField(blank=True, default=list, help_text='Detected competencies with levels')),
                ('full_feedback', models.JSONField(blank=True, default=dict, help_text='Structured feedback (correctness, missed_requirements, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_feedback',
            },
        ),
        migrations.CreateModel(
            name='MissionArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('file', 'File'), ('github', 'GitHub'), ('notebook', 'Notebook'), ('video', 'Video'), ('screenshot', 'Screenshot')], db_index=True, default='file', help_text='Type of artifact', max_length=20)),
                ('url', models.URLField(help_text='S3 signed URL, GitHub link, or video URL', max_length=500)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mission_artifacts',
            },
        ),
        migrations.CreateModel(
            name='MissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtask_number', models.IntegerField(help_text='Subtask number this file belongs to', validators=[django.core.validators.MinValueValidator(1)])),
                ('file_url', models.URLField(help_text='S3 or storage URL', max_length=500)),
                ('file_type', models.CharField(choices=[('log', 'Log File'), ('screenshot', 'Screenshot'), ('report', 'Report'), ('code', 'Code'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional file metadata')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mission_files',
            },
        ),
        migrations.CreateModel(
            name='MissionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('ai_reviewed', 'AI Reviewed'), ('in_ai_review', 'In AI Review'), ('mentor_review', 'Mentor Review'), ('in_mentor_review', 'In Mentor Review'), ('approved', 'Approved'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('revised', 'Revised')], db_index=True, default='not_started', max_length=20)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI review score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_score', models.DecimalField(blank=True, decimal_places=2, help_text='Mentor review score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_feedback', models.TextField(blank=True)),
                ('mentor_feedback', models.TextField(blank=True, help_text='Premium tier only')),
                ('notes', models.TextField(blank=True, help_text='Student notes to reviewer')),
                ('portfolio_item_id', models.UUIDField(blank=True, help_text='Auto-linked on approval', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ai_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('mentor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mission_submissions',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Mission code like "SIEM-03"', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('story', models.TextField(blank=True, help_text='Narrative context for the mission')),
                ('objectives', models.JSONField(blank=True, default=list, help_text='Array of mission objectives')),
                ('subtasks', models.JSONField(blank=True, default=list, help_text='Array of subtasks with dependencies and evidence_schema')),
                ('track', models.CharField(choices=[('defender', 'Defender'), ('offensive', 'Offensive'), ('grc', 'GRC'), ('innovation', 'Innovation'), ('leadership', 'Leadership')], db_index=True, help_text='Track: defender, offensive, grc, innovation, leadership', max_length=20)),
                ('tier', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mastery', 'Mastery'), ('capstone', 'Capstone')], db_index=True, help_text='Tier: beginner, intermediate, advanced, mastery, capstone', max_length=20)),
                ('difficulty', models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite')], db_index=True, max_length=20)),
                ('type', models.CharField(choices=[('lab', 'Lab'), ('scenario', 'Scenario'), ('project', 'Project'), ('capstone', 'Capstone')], db_index=True, default='lab', max_length=20)),
                ('track_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('track_key', models.CharField(blank=True, db_index=True, help_text='Track key like "soc_analyst"', max_length=50)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, help_text='Estimated minutes to complete', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('est_hours', models.IntegerField(blank=True, help_text='Estimated hours to complete (legacy)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('requires_mentor_review', models.BooleanField(default=False, help_text='Requires premium mentor review')),
                ('recipe_recommendations', models.JSONField(blank=True, default=list, help_text='Array of recipe IDs for micro-skills')),
                ('success_criteria', models.JSONField(blank=True, default=dict, help_text='Rubric criteria for scoring')),
                ('competencies', models.JSONField(blank=True, default=list, help_text='["SIEM", "Alerting", "IR"]')),
                ('requirements', models.JSONField(blank=True, default=dict, help_text='Mission requirements template, file types, etc.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'missions',
                'indexes': [models.Index(fields=['difficulty', 'track_id'], name='missions_difficu_85295d_idx'), models.Index(fields=['track_key', 'difficulty'], name='missions_track_k_37486a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MissionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('ai_reviewed', 'AI Reviewed'), ('mentor_review', 'Mentor Review'), ('approved', 'Approved'), ('failed', 'Failed'), ('revision_requested', 'Revision Requested')], db_index=True, default='locked', max_length=20)),
                ('current_subtask', models.IntegerField(default=1, help_text='Current subtask number (1-indexed)')),
                ('subtasks_progress', models.JSONField(blank=True, default=dict, help_text='{1: {completed: true, evidence: []}, ...}')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI review score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_score', models.DecimalField(blank=True, decimal_places=2, help_text='Mentor review score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_status', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], max_length=20, null=True)),
                ('reflection', models.TextField(blank=True, help_text='Student reflection on mission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='missions.mission')),
            ],
            options={
                'db_table': 'mission_progress',
            },
        ),
    ]
