# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mxp_mission_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionfile',
            name='mission_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='missions.missionprogress'),
        ),
        migrations.AddField(
            model_name='missionsubmission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missionsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionartifact',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='missions.missionsubmission'),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_detail', to='missions.missionsubmission'),
        ),
        migrations.AddIndex(
            model_name='missionprogress',
            index=models.Index(fields=['user', 'status'], name='mission_pro_user_id_1708b3_idx'),
        ),
        migrations.AddIndex(
            model_name='missionprogress',
            index=models.Index(fields=['mission', 'status'], name='mission_pro_mission_5557d6_idx'),
        ),
        migrations.AddIndex(
            model_name='missionprogress',
            index=models.Index(fields=['user', 'mission'], name='mission_pro_user_id_6db1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='missionprogress',
            index=models.Index(fields=['user', 'final_status'], name='mission_pro_user_id_ddb499_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='missionprogress',
            unique_together={('mission', 'user')},
        ),
        migrations.AddIndex(
            model_name='missionfile',
            index=models.Index(fields=['mission_progress', 'subtask_number'], name='mission_fil_mission_46f0df_idx'),
        ),
        migrations.AddIndex(
            model_name='missionfile',
            index=models.Index(fields=['mission_progress', 'uploaded_at'], name='mission_fil_mission_6b92ae_idx'),
        ),
        migrations.AddIndex(
            model_name='missionsubmission',
            index=models.Index(fields=['user', 'status'], name='mission_sub_user_id_fc6b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='missionsubmission',
            index=models.Index(fields=['mission', 'status'], name='mission_sub_mission_18452d_idx'),
        ),
        migrations.AddIndex(
            model_name='missionsubmission',
            index=models.Index(fields=['user', 'mission'], name='mission_sub_user_id_103dc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='missionsubmission',
            unique_together={('mission', 'user')},
        ),
        migrations.AddIndex(
            model_name='missionartifact',
            index=models.Index(fields=['submission', 'kind'], name='mission_art_submiss_7b7a76_idx'),
        ),
        migrations.AddIndex(
            model_name='missionartifact',
            index=models.Index(fields=['submission', 'created_at'], name='mission_art_submiss_072bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['submission'], name='ai_feedback_submiss_c7f4b4_idx'),
        ),
    ]
