# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICoachMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('context', models.CharField(blank=True, help_text='Context: habit_help, goal_revision, etc.', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (habit_id, goal_id, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ai_coach_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AICoachSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('habit', 'Habit'), ('goal', 'Goal'), ('reflection', 'Reflection'), ('mission', 'Mission'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('prompt_count', models.IntegerField(default=0, help_text='Number of prompts in this session', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_coach_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target', models.IntegerField(help_text='Target value for progress calculation', validators=[django.core.validators.MinValueValidator(1)])),
                ('current', models.IntegerField(default=0, help_text='Current value toward target', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20)),
                ('mentor_feedback', models.TextField(blank=True, default='', help_text='Mentor feedback (7-tier only)', null=True)),
                ('subscription_tier', models.CharField(blank=True, help_text='Subscription tier when goal was created', max_length=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coaching_goals',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='"Learn", "Practice", "Reflect", or custom', max_length=255)),
                ('type', models.CharField(choices=[('core', 'Core'), ('custom', 'Custom')], db_index=True, default='custom', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Daily or weekly frequency', max_length=20)),
                ('streak', models.IntegerField(default=0, help_text='Current streak days', validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest streak achieved', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coaching_habits',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='YYYY-MM-DD')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('missed', 'Missed')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coaching_habit_logs',
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='YYYY-MM-DD')),
                ('content', models.TextField()),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], help_text='User-selected or AI-computed sentiment', max_length=20, null=True)),
                ('emotion_tags', models.JSONField(blank=True, default=list, help_text='Array of emotion tags: ["overwhelmed", "confident"]')),
                ('ai_insights', models.TextField(blank=True, help_text='AI-generated insights', null=True)),
                ('word_count', models.IntegerField(default=0, help_text='Word count for analytics', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coaching_reflections',
            },
        ),
    ]
