# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicoachsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_coach_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aicoachmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='coaching.aicoachsession'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='coaching.habit'),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_habit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reflection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_reflections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aicoachsession',
            index=models.Index(fields=['user', 'created_at'], name='ai_coach_se_user_id_86f8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='aicoachsession',
            index=models.Index(fields=['user', 'session_type'], name='ai_coach_se_user_id_6af19a_idx'),
        ),
        migrations.AddIndex(
            model_name='aicoachmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_coach_me_session_e9130d_idx'),
        ),
        migrations.AddIndex(
            model_name='aicoachmessage',
            index=models.Index(fields=['role'], name='ai_coach_me_role_0edd18_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='coaching_go_user_id_1907a5_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'type'], name='coaching_go_user_id_1ebef7_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'due_date'], name='coaching_go_user_id_f70fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_active'], name='coaching_ha_user_id_ef9833_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'type'], name='coaching_ha_user_id_a227ea_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'created_at'], name='coaching_ha_user_id_064770_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'date'], name='coaching_ha_user_id_022a38_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'date'], name='coaching_ha_habit_i_7fcbef_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'date', 'status'], name='coaching_ha_user_id_c51a32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'date')},
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['user', 'date'], name='coaching_re_user_id_8df0da_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['user', 'created_at'], name='coaching_re_user_id_139e38_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['sentiment'], name='coaching_re_sentime_fd3239_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reflection',
            unique_together={('user', 'date')},
        ),
    ]
