# Generated by Django 5.2.8 on 2026-01-17 14:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_initial'),
        ('users', '0004_add_metadata_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_analytics', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_missions_completed', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_time_spent_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('track_code', models.CharField(blank=True, max_length=50, null=True)),
                ('circle_level', models.IntegerField(default=1)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('modules_completed', models.IntegerField(default=0)),
                ('recipes_completed', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('replies_count', models.IntegerField(default=0)),
                ('helpful_votes_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Student Analytics',
                'db_table': 'coaching_student_analytics',
            },
        ),
        migrations.CreateModel(
            name='CommunityActivitySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_replies', models.IntegerField(default=0)),
                ('helpful_votes_given', models.IntegerField(default=0)),
                ('helpful_votes_received', models.IntegerField(default=0)),
                ('posts_last_30_days', models.IntegerField(default=0)),
                ('replies_last_30_days', models.IntegerField(default=0)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('activity_streak_days', models.IntegerField(default=0)),
                ('badges_earned', models.JSONField(default=list)),
                ('communities_joined', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coaching_community_activity_summary',
            },
        ),
        migrations.CreateModel(
            name='UserTrackProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_code', models.CharField(db_index=True, max_length=50)),
                ('circle_level', models.IntegerField(default=1)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('modules_completed', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('missions_completed', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('highest_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('readiness_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skills_mastered', models.JSONField(default=dict)),
                ('weak_areas', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_track_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coaching_user_track_progress',
            },
        ),
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(db_index=True, max_length=50)),
                ('context', models.CharField(db_index=True, max_length=100)),
                ('model_used', models.CharField(default='groq-llama', max_length=50)),
                ('advice', models.JSONField()),
                ('complexity_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coaching_coaching_sessions',
                'indexes': [models.Index(fields=['user', 'created_at'], name='coaching_co_user_id_1f382d_idx'), models.Index(fields=['trigger', 'created_at'], name='coaching_co_trigger_63d444_idx')],
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mentor_id', models.UUIDField(blank=True, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('mentor_feedback', models.TextField(blank=True)),
                ('session_notes', models.TextField(blank=True)),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mentor_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_mentorship_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coaching_mentorship_sessions',
                'indexes': [models.Index(fields=['user', 'status'], name='coaching_me_user_id_c69881_idx'), models.Index(fields=['scheduled_at'], name='coaching_me_schedul_c3a8fa_idx'), models.Index(fields=['mentor_id', 'status'], name='coaching_me_mentor__69eb03_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='not_started', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_score', models.IntegerField(default=100)),
                ('attempts_count', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('level', models.CharField(db_index=True, max_length=20)),
                ('skills_tagged', models.JSONField(default=list)),
                ('instructor_feedback', models.TextField(blank=True)),
                ('user_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_mission_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coaching_user_mission_progress',
                'indexes': [models.Index(fields=['user', 'status'], name='coaching_us_user_id_2b3d42_idx'), models.Index(fields=['mission_id', 'status'], name='coaching_us_mission_ad2485_idx'), models.Index(fields=['level', 'status'], name='coaching_us_level_6e0f1c_idx')],
                'unique_together': {('user', 'mission_id')},
            },
        ),
        migrations.CreateModel(
            name='UserRecipeProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('mastered', 'Mastered')], default='not_started', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_recipe_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coaching_user_recipe_progress',
                'indexes': [models.Index(fields=['user', 'status'], name='coaching_us_user_id_be938d_idx'), models.Index(fields=['recipe_id', 'status'], name='coaching_us_recipe__649f33_idx')],
                'unique_together': {('user', 'recipe_id')},
            },
        ),
    ]
